// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.
//
// Synurang transport for @grpc/grpc-js.
//
// PluginChannel implements grpc-js's ChannelInterface, the counterpart of Go's
// grpc.ClientConnInterface, on top of a Synurang plugin host. Pass it as
// `channelOverride` and a generated grpc-js client runs unchanged over FFI:
//
//   // Network gRPC (the usual way)
//   const client = new GreeterClient("localhost:50051", grpc.credentials.createInsecure());
//
//   // Synurang FFI
//   const client = new GreeterClient("synurang", grpc.credentials.createInsecure(), {
//     channelOverride: new PluginChannel(host, GreeterService),
//   });
//
// Unary and streaming calls, ServiceError, deadlines, cancellation and
// interceptors behave as they do over the network. The plugin ABI carries no
// metadata: outgoing metadata is ignored and responses carry none, except that
// a structured plugin error (core.v1.Error) is exposed through the standard
// `grpc-status-details-bin` trailer.

import * as grpc from "@grpc/grpc-js";

type Call = ReturnType<grpc.ChannelInterface["createCall"]>;
type CallListener = Parameters<Call["start"]>[1];
type MessageContext = Parameters<Call["sendMessageWithContext"]>[0];
type ParentCall = Parameters<grpc.ChannelInterface["createCall"]>[3];
type ChannelRef = ReturnType<grpc.ChannelInterface["getChannelzRef"]>;
type Timer = ReturnType<typeof setTimeout>;

/**
 * Bridge to a Synurang plugin: `Synurang_Invoke_<Service>` and
 * `Synurang_Stream_*` exposed by a native addon, an FFI library, a wasm module
 * and so on.
 *
 * `serviceName` is the service identifier used in the plugin symbols (for
 * example "GreeterService") and `methodName` is the full gRPC method path.
 * Methods may return results directly or as promises. Report a plugin error
 * payload by throwing `FfiError.fromPayload(payload)`. Returned byte arrays
 * must not be reused by the host.
 */
export interface PluginChannelHost {
  invoke(serviceName: string, methodName: string, data: Uint8Array): Uint8Array | PromiseLike<Uint8Array>;
  /** Required for streaming methods. */
  openStream?(serviceName: string, methodName: string): PluginChannelStream | PromiseLike<PluginChannelStream>;
}

/** Common call transport implemented by createNativeHost/createWasmHost and
 * WorkerHost. Unary uses the same cancellable lifecycle as streaming. */
export interface PluginCallTransport {
  open(method: { path: string; requestStream: boolean; responseStream: boolean },
    options?: { signal?: AbortSignal; timeoutMs?: number }): PromiseLike<{
      send(data: Uint8Array): Promise<void>;
      halfClose(): Promise<void>;
      recv(): Promise<Uint8Array | null>;
      cancel(code?: number): void;
      close(): Promise<void>;
    }>;
}
function isCallTransport(host: PluginChannelHost | PluginCallTransport): host is PluginCallTransport {
  return typeof (host as Partial<PluginCallTransport>).open === 'function';
}

/**
 * One open plugin stream. Sends are issued one at a time; a receive may be
 * pending while a send is in progress.
 */
export interface PluginChannelStream {
  send(data: Uint8Array): void | PromiseLike<void>;
  /** Returns null once the plugin has finished the stream. */
  recv(): Uint8Array | null | PromiseLike<Uint8Array | null>;
  closeSend(): void | PromiseLike<void>;
  /** Releases the stream. May be called while a send or receive is pending. */
  close(): void;
}

export interface PluginChannelOptions {
  /** Reported by getTarget() and call.getPeer(). Defaults to "synurang". */
  target?: string;
}

const GRPC_STATUS_DETAILS_KEY = "grpc-status-details-bin";
const CORE_ERROR_TYPE_URL = "type.googleapis.com/core.v1.Error";
const MAX_TIMEOUT_TIME = 2147483647;
const CHANNEL_SHUT_DOWN = "Channel has been shut down";

/**
 * Structured error returned by a Synurang plugin (core.v1.Error), the same
 * FfiError that the Go, Python and other hosts expose.
 */
export class FfiError extends Error {
  /** Application-specific error code. */
  readonly code: number;
  /** gRPC status code carried by the plugin. */
  readonly grpcCode: number;
  /** The payload this error was decoded from, if any. */
  readonly payload: Uint8Array | undefined;

  constructor(message: string, code = 0, grpcCode: number = grpc.status.UNKNOWN, payload?: Uint8Array) {
    super(message);
    this.name = "FfiError";
    this.code = code;
    this.grpcCode = grpcCode;
    this.payload = payload;
  }

  /**
   * Decodes a core.v1.Error payload. Without a message field the payload is
   * read as UTF-8 text, as older plugins returned plain text errors.
   */
  static fromPayload(payload: Uint8Array): FfiError {
    const data = new Uint8Array(payload);
    let code = 0;
    let grpcCode = 0;
    let message: string | undefined;
    for (let pos = 0; pos < data.length;) {
      const tag = readVarint(data, pos);
      if (tag === undefined || tag.value === 0) break;
      pos = tag.next;
      const field = tag.value >>> 3;
      const wire = tag.value & 7;
      if (field === 1 && wire === 0) {
        const value = readVarint(data, pos);
        if (value === undefined) break;
        code = value.value;
        pos = value.next;
      } else if (field === 2 && wire === 2) {
        const value = readBytes(data, pos);
        if (value === undefined) break;
        message = utf8(value.value);
        pos = value.next;
      } else if (field === 3 && wire === 0) {
        const value = readVarint(data, pos);
        if (value === undefined) break;
        grpcCode = value.value;
        pos = value.next;
      } else {
        const next = skipField(data, pos, wire);
        if (next === undefined) break;
        pos = next;
      }
    }
    return new FfiError(message ?? utf8(data), code, grpcCode, data);
  }

  /**
   * Recovers a plugin error from a ServiceError or StatusObject. Also works
   * for network calls whose server attached core.v1.Error to the status
   * details, as grpc-go does with status.WithDetails.
   */
  static fromStatus(status: { metadata?: grpc.Metadata | null }): FfiError | undefined {
    for (const value of status.metadata?.get(GRPC_STATUS_DETAILS_KEY) ?? []) {
      if (typeof value === "string") continue;
      const detail = findStatusDetail(value, CORE_ERROR_TYPE_URL);
      if (detail !== undefined) return FfiError.fromPayload(detail);
    }
    return undefined;
  }
}

interface MethodKind {
  readonly requestStream: boolean;
  readonly responseStream: boolean;
}

interface PendingWrite {
  readonly message: Buffer;
  readonly context: MessageContext;
}

interface StateWatcher {
  readonly currentState: grpc.connectivityState;
  readonly callback: (error?: Error) => void;
  timer?: Timer;
}

let nextChannelId = 0;
let nextCallNumber = 0;

/**
 * grpc-js channel that routes calls to a Synurang plugin host. `services`
 * lists the grpc-js service definitions whose methods the plugin serves; any
 * generated definition works, including those of other code generators.
 */
export class PluginChannel implements grpc.ChannelInterface {
  private readonly methods = new Map<string, MethodKind>();
  private readonly serviceNames = new Set<string>();
  private readonly watchers = new Set<StateWatcher>();
  private readonly target: string;
  private readonly channelzRef: ChannelRef;
  private state: grpc.connectivityState = grpc.connectivityState.READY;

  constructor(
    private readonly host: PluginChannelHost | PluginCallTransport,
    services: grpc.ServiceDefinition | readonly grpc.ServiceDefinition[],
    options: PluginChannelOptions = {},
  ) {
    const definitions = (Array.isArray(services) ? services : [services]) as readonly grpc.ServiceDefinition[];
    for (const definition of definitions) {
      for (const method of Object.values(definition)) {
        this.methods.set(method.path, { requestStream: method.requestStream, responseStream: method.responseStream });
        this.serviceNames.add(serviceOfPath(method.path));
      }
    }
    this.target = options.target ?? "synurang";
    this.channelzRef = { kind: "channel", id: ++nextChannelId, name: this.target } as unknown as ChannelRef;
  }

  close(): void {
    if (this.state === grpc.connectivityState.SHUTDOWN) return;
    this.state = grpc.connectivityState.SHUTDOWN;
    for (const watcher of [...this.watchers]) {
      this.watchers.delete(watcher);
      clearTimeout(watcher.timer);
      watcher.callback();
    }
  }

  getTarget(): string {
    return this.target;
  }

  getConnectivityState(): grpc.connectivityState {
    return this.state;
  }

  watchConnectivityState(
    currentState: grpc.connectivityState,
    deadline: Date | number,
    callback: (error?: Error) => void,
  ): void {
    if (this.state === grpc.connectivityState.SHUTDOWN) throw new Error(CHANNEL_SHUT_DOWN);
    if (currentState !== this.state) {
      process.nextTick(callback);
      return;
    }
    const watcher: StateWatcher = { currentState, callback };
    if (deadline !== Infinity) {
      const remaining = (deadline instanceof Date ? deadline.getTime() : deadline) - Date.now();
      if (deadline === -Infinity || remaining <= 0) {
        process.nextTick(callback, new Error("Deadline passed without connectivity state change"));
        return;
      }
      watcher.timer = setTimeout(() => {
        this.watchers.delete(watcher);
        callback(new Error("Deadline passed without connectivity state change"));
      }, remaining);
    }
    this.watchers.add(watcher);
  }

  getChannelzRef(): ChannelRef {
    return this.channelzRef;
  }

  createCall(
    method: string,
    deadline: grpc.Deadline,
    _host: string | null | undefined,
    parentCall: ParentCall,
    propagateFlags: number | null | undefined,
  ): Call {
    if (typeof method !== "string") {
      throw new TypeError("Channel#createCall: method must be a string");
    }
    if (!(typeof deadline === "number" || deadline instanceof Date)) {
      throw new TypeError("Channel#createCall: deadline must be a number or Date");
    }
    if (this.state === grpc.connectivityState.SHUTDOWN) throw new Error(CHANNEL_SHUT_DOWN);
    return new PluginCall(
      this.host,
      method,
      this.methods.get(method),
      this.serviceNames.has(serviceOfPath(method)),
      this.target,
      deadline,
      parentCall,
      propagateFlags,
    );
  }
}

/**
 * One call on a PluginChannel. Delivery follows grpc-js's own transport:
 * messages are pushed one per startRead(), a non-OK status ends the call
 * immediately, and an OK status waits until every message was delivered.
 */
class PluginCall implements Call {
  private readonly callNumber = ++nextCallNumber;
  private readonly serviceName: string;
  private listener: CallListener | null = null;
  private finalStatus: grpc.StatusObject | null = null;
  private statusOutput = false;
  private deadlineTimer: Timer | undefined;

  private metadataReceived = false;
  private canPush = false;
  private pushPending = false;
  private readsClosed = false;
  private readonly incoming: Buffer[] = [];

  private request: Buffer | undefined;
  private readonly writes: PendingWrite[] = [];
  private writing = false;
  private halfClosed = false;
  private closeSendIssued = false;
  private writeFailure: { error: unknown } | undefined;
  private requestClosed = false;

  private stream: PluginChannelStream | undefined;
  private reading = false;
  private nativeClosed = false;
  private readonly abort = new AbortController();
  private readonly deadline: grpc.Deadline;

  constructor(
    private readonly host: PluginChannelHost | PluginCallTransport,
    private readonly method: string,
    private readonly kind: MethodKind | undefined,
    private readonly serviceKnown: boolean,
    private readonly peer: string,
    deadline: grpc.Deadline,
    parentCall: ParentCall,
    propagateFlags: number | null | undefined,
  ) {
    this.serviceName = pluginServiceName(method);
    const flags = propagateFlags ?? grpc.propagate.DEFAULTS;
    if (parentCall) {
      if (flags & grpc.propagate.CANCELLATION) {
        parentCall.on("cancelled", () => {
          this.cancelWithStatus(grpc.status.CANCELLED, "Cancelled by parent call");
        });
      }
      if (flags & grpc.propagate.DEADLINE) {
        deadline = minDeadline(deadline, parentCall.getDeadline());
      }
    }
    this.deadline = deadline;
    this.runDeadlineTimer(deadline);
  }

  start(_metadata: grpc.Metadata, listener: CallListener): void {
    this.listener = listener;
    if (this.finalStatus !== null) return;
    const kind = this.kind;
    if (kind === undefined) {
      const service = serviceOfPath(this.method);
      const details = this.serviceKnown
        ? `unknown method ${this.method.slice(this.method.lastIndexOf("/") + 1)} for service ${service}`
        : `unknown service ${service}`;
      this.endCall(makeStatus(grpc.status.UNIMPLEMENTED, details));
      return;
    }
    if (isCallTransport(this.host) || kind.requestStream || kind.responseStream) this.dispatch(() => this.openStream());
  }

  sendMessageWithContext(context: MessageContext, message: Buffer): void {
    if (this.kind !== undefined && (isCallTransport(this.host) || this.kind.requestStream || this.kind.responseStream)) {
      this.writes.push({ message, context });
      this.flushWrites();
      return;
    }
    this.request = message;
    process.nextTick(() => context.callback?.());
  }

  halfClose(): void {
    if (this.halfClosed) return;
    this.halfClosed = true;
    const kind = this.kind;
    if (kind === undefined || this.finalStatus !== null) return;
    if (isCallTransport(this.host) || kind.requestStream || kind.responseStream) {
      this.flushWrites();
      return;
    }
    const request = this.request ?? Buffer.alloc(0);
    const host = this.host as PluginChannelHost;
    this.dispatch(() => {
      settle(() => host.invoke(this.serviceName, this.method, request))
        .then((response) => {
          if (this.finalStatus !== null) return;
          this.receive(toBuffer(response));
          this.readsClosed = true;
          this.endCall(makeStatus(grpc.status.OK, ""));
        })
        .catch((error: unknown) => this.endCall(statusFromError(error)));
    });
  }

  startRead(): void {
    if (this.finalStatus !== null && this.finalStatus.code !== grpc.status.OK) {
      this.readsClosed = true;
      this.maybeOutputStatus();
      return;
    }
    this.canPush = true;
    const next = this.incoming.shift();
    if (next !== undefined) {
      this.push(next);
      return;
    }
    this.pump();
  }

  cancelWithStatus(code: grpc.status, details: string): void {
    this.endCall(makeStatus(code, details));
  }

  getPeer(): string {
    return this.peer;
  }

  getCallNumber(): number {
    return this.callNumber;
  }

  setCredentials(): void {
    // Call credentials produce metadata, which the plugin ABI does not carry.
  }

  getAuthContext(): null {
    return null;
  }

  /**
   * Starts plugin work on the next tick, so an already expired deadline or a
   * cancel issued right after the call was made never reaches the plugin, as
   * such a call would not reach a network server.
   */
  private dispatch(work: () => void): void {
    process.nextTick(() => {
      if (this.finalStatus === null) work();
    });
  }

  private openStream(): void {
    const host = this.host;
    if (isCallTransport(host)) {
      const deadline = this.deadline instanceof Date ? this.deadline.getTime() : this.deadline;
      const timeoutMs = Number.isFinite(deadline) ? Math.max(0, Math.ceil(deadline - Date.now())) : undefined;
      settle(() => host.open({ path: this.method, ...this.kind! }, { signal: this.abort.signal, timeoutMs })).then(call => {
        const stream: PluginChannelStream = {
          send: data => call.send(data), recv: () => call.recv(), closeSend: () => call.halfClose(),
          close: () => {
            const code = this.finalStatus?.code;
            if (code !== undefined && code !== grpc.status.OK) call.cancel(code);
            void call.close().catch(() => {});
          },
        };
        if (this.nativeClosed) { closeQuietly(stream); return; }
        this.stream = stream;
        this.flushWrites();
        this.pump();
      }, error => this.endCall(statusFromError(error)));
      return;
    }
    if (typeof host.openStream !== "function") {
      this.endCall(makeStatus(grpc.status.UNIMPLEMENTED, `plugin host does not support streaming for ${this.method}`));
      return;
    }
    settle(() => host.openStream!(this.serviceName, this.method)).then(
      (stream) => {
        if (stream == null) {
          this.endCall(makeStatus(grpc.status.UNKNOWN, `plugin host returned no stream for ${this.method}`));
          return;
        }
        if (this.nativeClosed) {
          closeQuietly(stream);
          return;
        }
        this.stream = stream;
        this.flushWrites();
        this.pump();
      },
      (error: unknown) => this.endCall(statusFromError(error)),
    );
  }

  private flushWrites(): void {
    if (this.writing) return;
    if (this.finalStatus !== null || this.writeFailure !== undefined || this.requestClosed) {
      this.dropWrites();
      return;
    }
    const stream = this.stream;
    if (stream === undefined) return;
    const write = this.writes.shift();
    if (write !== undefined) {
      this.writing = true;
      settle(() => stream.send(write.message)).then(
        () => {
          this.writing = false;
          process.nextTick(() => write.context.callback?.());
          this.flushWrites();
        },
        (error: unknown) => {
          this.writing = false;
          process.nextTick(() => write.context.callback?.());
          this.onWriteError(error);
          this.flushWrites();
        },
      );
      return;
    }
    if (this.halfClosed && !this.closeSendIssued) {
      this.closeSendIssued = true;
      this.writing = true;
      settle(() => stream.closeSend()).then(
        () => {
          this.writing = false;
        },
        (error: unknown) => {
          this.writing = false;
          this.onWriteError(error);
        },
      );
    }
  }

  private dropWrites(): void {
    for (const write of this.writes.splice(0)) {
      process.nextTick(() => write.context.callback?.());
    }
  }

  private onWriteError(error: unknown): void {
    if (this.finalStatus !== null) return;
    if (isCallTransport(this.host) && error instanceof Error && error.name === 'RequestClosedError') {
      this.requestClosed = true;
      this.dropWrites();
      this.pump();
      return;
    }
    const status = structuredStatus(error);
    if (status !== undefined) {
      this.endCall(status);
      return;
    }
    // A plugin that already finished the stream rejects further sends. Its
    // receive side reports the real status; a clean EOF becomes a write error.
    if (this.writeFailure === undefined) {
      this.writeFailure = { error };
      const stream = this.stream;
      if (stream !== undefined && !this.closeSendIssued) {
        this.closeSendIssued = true;
        settle(() => stream.closeSend()).catch(() => undefined);
      }
    }
    this.pump();
  }

  private pump(): void {
    const stream = this.stream;
    if (stream === undefined || this.reading || this.readsClosed || this.finalStatus !== null) return;
    // Read ahead at most one undelivered message, so a failed stream reports
    // its status promptly without buffering an unbounded response stream.
    if (!this.canPush && this.incoming.length > 0) return;
    this.reading = true;
    settle(() => stream.recv())
      .then((data) => {
        this.reading = false;
        if (this.finalStatus !== null) return;
        if (data == null) {
          this.readsClosed = true;
          const failure = this.writeFailure;
          this.endCall(
            failure === undefined
              ? makeStatus(grpc.status.OK, "")
              : makeStatus(grpc.status.UNAVAILABLE, `Write error: ${errorMessage(failure.error)}`),
          );
          return;
        }
        this.receive(toBuffer(data));
        if (!isCallTransport(this.host) && this.kind !== undefined && !this.kind.responseStream) {
          this.readsClosed = true;
          this.endCall(makeStatus(grpc.status.OK, ""));
          return;
        }
        this.pump();
      })
      .catch((error: unknown) => {
        this.reading = false;
        this.endCall(statusFromError(error));
      });
  }

  private receive(message: Buffer): void {
    if (!this.metadataReceived) {
      this.metadataReceived = true;
      const metadata = new grpc.Metadata();
      process.nextTick(() => {
        if (!this.statusOutput) this.listener?.onReceiveMetadata(metadata);
      });
    }
    if (this.canPush) {
      this.push(message);
    } else {
      this.incoming.push(message);
    }
  }

  private push(message: Buffer): void {
    this.canPush = false;
    this.pushPending = true;
    process.nextTick(() => {
      this.pushPending = false;
      if (this.statusOutput) return;
      this.listener?.onReceiveMessage(message);
      this.maybeOutputStatus();
      this.pump();
    });
  }

  private endCall(status: grpc.StatusObject): void {
    if (this.finalStatus === null || this.finalStatus.code === grpc.status.OK) {
      this.finalStatus = status;
      this.maybeOutputStatus();
    }
    this.dropWrites();
    this.closeNative();
  }

  private maybeOutputStatus(): void {
    const status = this.finalStatus;
    if (status === null || this.statusOutput) return;
    if (
      status.code !== grpc.status.OK ||
      (this.readsClosed && this.incoming.length === 0 && !this.pushPending)
    ) {
      this.statusOutput = true;
      clearTimeout(this.deadlineTimer);
      process.nextTick(() => this.listener?.onReceiveStatus(status));
    }
  }

  private closeNative(): void {
    if (this.nativeClosed) return;
    this.nativeClosed = true;
    if (this.stream !== undefined) closeQuietly(this.stream);
    this.abort.abort();
  }

  private runDeadlineTimer(deadline: grpc.Deadline): void {
    let timeout = (deadline instanceof Date ? deadline.getTime() : deadline) - Date.now();
    if (timeout < 0) {
      timeout = 0;
    } else if (timeout > MAX_TIMEOUT_TIME) {
      return;
    }
    const onDeadline = () => this.cancelWithStatus(grpc.status.DEADLINE_EXCEEDED, "Deadline exceeded");
    if (timeout <= 0) {
      process.nextTick(onDeadline);
    } else {
      this.deadlineTimer = setTimeout(onDeadline, timeout);
    }
  }
}

function makeStatus(code: grpc.status, details: string): grpc.StatusObject {
  return { code, details, metadata: new grpc.Metadata() };
}

function settle<T>(operation: () => T | PromiseLike<T>): Promise<T> {
  return new Promise<T>((resolve) => resolve(operation()));
}

function closeQuietly(stream: PluginChannelStream): void {
  try {
    stream.close();
  } catch {
    // The call has already ended; a failing release has nowhere to report.
  }
}

function toBuffer(data: Uint8Array): Buffer {
  if (!ArrayBuffer.isView(data)) throw new TypeError("plugin host must return a Uint8Array");
  return Buffer.isBuffer(data) ? data : Buffer.from(data.buffer, data.byteOffset, data.byteLength);
}

function minDeadline(...deadlines: grpc.Deadline[]): number {
  let min = Infinity;
  for (const deadline of deadlines) {
    const ms = deadline instanceof Date ? deadline.getTime() : deadline;
    if (ms < min) min = ms;
  }
  return min;
}

function serviceOfPath(path: string): string {
  return path.slice(1, path.lastIndexOf("/"));
}

/** Service identifier of the plugin symbols, as the code generator names it. */
function pluginServiceName(path: string): string {
  const service = serviceOfPath(path);
  let name = "";
  let capitalize = true;
  for (const ch of service.slice(service.lastIndexOf(".") + 1)) {
    if (ch === "_" || ch === "-") {
      capitalize = true;
      continue;
    }
    if (name === "" && ch >= "0" && ch <= "9") name += "X";
    name += capitalize ? ch.toUpperCase() : ch;
    capitalize = false;
  }
  return name;
}

function errorMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  try {
    return String(error);
  } catch {
    return "unknown error";
  }
}

function toInt32(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) ? value | 0 : 0;
}

function errorStatusCode(value: unknown): grpc.status | undefined {
  return typeof value === "number" &&
    Number.isInteger(value) &&
    value > grpc.status.OK &&
    value <= grpc.status.UNAUTHENTICATED
    ? (value as grpc.status)
    : undefined;
}

/** Status for FfiError-like and StatusObject-like host errors. */
function structuredStatus(error: unknown): grpc.StatusObject | undefined {
  if (typeof error !== "object" || error === null) return undefined;
  const rpcError = error as { code?: unknown; message?: unknown; details?: unknown };
  const rpcCode = errorStatusCode(rpcError.code);
  if (rpcCode !== undefined && typeof rpcError.message === 'string' && rpcError.details instanceof Uint8Array) {
    const metadata = new grpc.Metadata();
    if (rpcError.details.byteLength) metadata.set(GRPC_STATUS_DETAILS_KEY,
      encodeStatus(rpcCode, rpcError.message, rpcError.details));
    return { code: rpcCode, details: rpcError.message, metadata };
  }
  const candidate = error as Partial<FfiError> & Partial<grpc.StatusObject>;
  if (typeof candidate.grpcCode === "number" && typeof candidate.message === "string") {
    const pluginCode = toInt32(candidate.grpcCode);
    const code = errorStatusCode(pluginCode) ?? grpc.status.UNKNOWN;
    const message = candidate.message;
    const metadata = new grpc.Metadata();
    const detail = encodeCoreError(toInt32(candidate.code), message, pluginCode);
    metadata.set(GRPC_STATUS_DETAILS_KEY, encodeStatus(code, message, detail));
    return { code, details: message, metadata };
  }
  const code = errorStatusCode(candidate.code);
  if (code !== undefined && typeof candidate.details === "string") {
    const metadata = candidate.metadata instanceof grpc.Metadata ? candidate.metadata : new grpc.Metadata();
    return { code, details: candidate.details, metadata };
  }
  return undefined;
}

function statusFromError(error: unknown): grpc.StatusObject {
  return structuredStatus(error) ?? makeStatus(grpc.status.UNKNOWN, errorMessage(error));
}

// Minimal protobuf wire helpers for core.v1.Error and google.rpc.Status.

interface Decoded<T> {
  readonly value: T;
  readonly next: number;
}

/** Reads a varint and returns its low 32 bits as a signed integer. */
function readVarint(data: Uint8Array, pos: number): Decoded<number> | undefined {
  let value = 0;
  for (let shift = 0; shift < 70; shift += 7) {
    if (pos >= data.length) return undefined;
    const byte = data[pos++];
    if (shift < 35) value += (byte & 0x7f) * 2 ** shift;
    if ((byte & 0x80) === 0) return { value: value | 0, next: pos };
  }
  return undefined;
}

function readBytes(data: Uint8Array, pos: number): Decoded<Uint8Array> | undefined {
  const length = readVarint(data, pos);
  if (length === undefined || length.value < 0 || length.value > data.length - length.next) return undefined;
  const end = length.next + length.value;
  return { value: data.subarray(length.next, end), next: end };
}

function skipField(data: Uint8Array, pos: number, wire: number): number | undefined {
  switch (wire) {
    case 0:
      return readVarint(data, pos)?.next;
    case 1:
      return pos + 8 <= data.length ? pos + 8 : undefined;
    case 2:
      return readBytes(data, pos)?.next;
    case 5:
      return pos + 4 <= data.length ? pos + 4 : undefined;
    default:
      return undefined;
  }
}

function utf8(data: Uint8Array): string {
  return Buffer.from(data.buffer, data.byteOffset, data.byteLength).toString("utf8");
}

/** Returns the value of the first google.protobuf.Any detail with `typeUrl`. */
function findStatusDetail(status: Uint8Array, typeUrl: string): Uint8Array | undefined {
  for (let pos = 0; pos < status.length;) {
    const tag = readVarint(status, pos);
    if (tag === undefined || tag.value === 0) return undefined;
    const wire = tag.value & 7;
    if (tag.value >>> 3 !== 3 || wire !== 2) {
      const next = skipField(status, tag.next, wire);
      if (next === undefined) return undefined;
      pos = next;
      continue;
    }
    const any = readBytes(status, tag.next);
    if (any === undefined) return undefined;
    pos = any.next;
    let url = "";
    let value: Uint8Array = new Uint8Array(0);
    for (let at = 0; at < any.value.length;) {
      const anyTag = readVarint(any.value, at);
      if (anyTag === undefined || anyTag.value === 0) break;
      const anyWire = anyTag.value & 7;
      const field = anyTag.value >>> 3;
      if ((field === 1 || field === 2) && anyWire === 2) {
        const bytes = readBytes(any.value, anyTag.next);
        if (bytes === undefined) break;
        if (field === 1) url = utf8(bytes.value);
        else value = bytes.value;
        at = bytes.next;
      } else {
        const next = skipField(any.value, anyTag.next, anyWire);
        if (next === undefined) break;
        at = next;
      }
    }
    if (url === typeUrl) return value;
  }
  return undefined;
}

class ProtoWriter {
  private readonly out: number[] = [];

  int32(field: number, value: number): void {
    if (value === 0) return;
    this.varint((field << 3) | 0);
    if (value < 0) {
      // Negative int32 values are sign-extended to ten bytes.
      let low = value >>> 0;
      for (let i = 0; i < 4; i++) {
        this.out.push((low & 0x7f) | 0x80);
        low >>>= 7;
      }
      this.out.push(low | 0xf0, 0xff, 0xff, 0xff, 0xff, 0x01);
      return;
    }
    this.varint(value);
  }

  bytes(field: number, value: Uint8Array): void {
    this.varint((field << 3) | 2);
    this.varint(value.length);
    for (const byte of value) this.out.push(byte);
  }

  string(field: number, value: string): void {
    if (value !== "") this.bytes(field, Buffer.from(value, "utf8"));
  }

  finish(): Buffer {
    return Buffer.from(this.out);
  }

  private varint(value: number): void {
    let remaining = value >>> 0;
    while (remaining > 0x7f) {
      this.out.push((remaining & 0x7f) | 0x80);
      remaining >>>= 7;
    }
    this.out.push(remaining);
  }
}

function encodeCoreError(code: number, message: string, grpcCode: number): Buffer {
  const writer = new ProtoWriter();
  writer.int32(1, code);
  writer.string(2, message);
  writer.int32(3, grpcCode);
  return writer.finish();
}

function encodeStatus(code: number, message: string, coreError: Uint8Array): Buffer {
  const any = new ProtoWriter();
  any.string(1, CORE_ERROR_TYPE_URL);
  if (coreError.length > 0) any.bytes(2, coreError);
  const writer = new ProtoWriter();
  writer.int32(1, code);
  writer.string(2, message);
  writer.bytes(3, any.finish());
  return writer.finish();
}
