// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: activex.proto

package api

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActiveXProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dispid        int32                  `protobuf:"varint,1,opt,name=dispid,proto3" json:"dispid,omitempty"`                       // COM DISPID number
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // COM property/method name (e.g., "Rows")
	Custom        bool                   `protobuf:"varint,3,opt,name=custom,proto3" json:"custom,omitempty"`                       // Emit constant + name entry, but skip dispatch case
	Olecolor      bool                   `protobuf:"varint,4,opt,name=olecolor,proto3" json:"olecolor,omitempty"`                   // Apply olecolor <-> argb conversion
	SetMethod     string                 `protobuf:"bytes,5,opt,name=set_method,json=setMethod,proto3" json:"set_method,omitempty"` // Override: explicit setter RPC name (default: "Set" + name)
	GetMethod     string                 `protobuf:"bytes,6,opt,name=get_method,json=getMethod,proto3" json:"get_method,omitempty"` // Override: explicit getter RPC name (default: "Get" + name)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveXProperty) Reset() {
	*x = ActiveXProperty{}
	mi := &file_activex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveXProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveXProperty) ProtoMessage() {}

func (x *ActiveXProperty) ProtoReflect() protoreflect.Message {
	mi := &file_activex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveXProperty.ProtoReflect.Descriptor instead.
func (*ActiveXProperty) Descriptor() ([]byte, []int) {
	return file_activex_proto_rawDescGZIP(), []int{0}
}

func (x *ActiveXProperty) GetDispid() int32 {
	if x != nil {
		return x.Dispid
	}
	return 0
}

func (x *ActiveXProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActiveXProperty) GetCustom() bool {
	if x != nil {
		return x.Custom
	}
	return false
}

func (x *ActiveXProperty) GetOlecolor() bool {
	if x != nil {
		return x.Olecolor
	}
	return false
}

func (x *ActiveXProperty) GetSetMethod() string {
	if x != nil {
		return x.SetMethod
	}
	return ""
}

func (x *ActiveXProperty) GetGetMethod() string {
	if x != nil {
		return x.GetMethod
	}
	return ""
}

type ActiveXServiceOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // DISPID constant prefix (e.g., "VFG")
	Properties    []*ActiveXProperty     `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveXServiceOption) Reset() {
	*x = ActiveXServiceOption{}
	mi := &file_activex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveXServiceOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveXServiceOption) ProtoMessage() {}

func (x *ActiveXServiceOption) ProtoReflect() protoreflect.Message {
	mi := &file_activex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveXServiceOption.ProtoReflect.Descriptor instead.
func (*ActiveXServiceOption) Descriptor() ([]byte, []int) {
	return file_activex_proto_rawDescGZIP(), []int{1}
}

func (x *ActiveXServiceOption) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ActiveXServiceOption) GetProperties() []*ActiveXProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

var file_activex_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.ServiceOptions)(nil),
		ExtensionType: (*ActiveXServiceOption)(nil),
		Field:         50100,
		Name:          "synurang.v1.activex_service",
		Tag:           "bytes,50100,opt,name=activex_service",
		Filename:      "activex.proto",
	},
}

// Extension fields to descriptor.ServiceOptions.
var (
	// optional synurang.v1.ActiveXServiceOption activex_service = 50100;
	E_ActivexService = &file_activex_proto_extTypes[0]
)

var File_activex_proto protoreflect.FileDescriptor

const file_activex_proto_rawDesc = "" +
	"\n" +
	"\ractivex.proto\x12\vsynurang.v1\x1a google/protobuf/descriptor.proto\"\xaf\x01\n" +
	"\x0fActiveXProperty\x12\x16\n" +
	"\x06dispid\x18\x01 \x01(\x05R\x06dispid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06custom\x18\x03 \x01(\bR\x06custom\x12\x1a\n" +
	"\bolecolor\x18\x04 \x01(\bR\bolecolor\x12\x1d\n" +
	"\n" +
	"set_method\x18\x05 \x01(\tR\tsetMethod\x12\x1d\n" +
	"\n" +
	"get_method\x18\x06 \x01(\tR\tgetMethod\"l\n" +
	"\x14ActiveXServiceOption\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12<\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2\x1c.synurang.v1.ActiveXPropertyR\n" +
	"properties:p\n" +
	"\x0factivex_service\x12\x1f.google.protobuf.ServiceOptions\x18\xb4\x87\x03 \x01(\v2!.synurang.v1.ActiveXServiceOptionR\x0eactivexService\x88\x01\x01B%Z#github.com/ivere27/synurang/pkg/apib\x06proto3"

var (
	file_activex_proto_rawDescOnce sync.Once
	file_activex_proto_rawDescData []byte
)

func file_activex_proto_rawDescGZIP() []byte {
	file_activex_proto_rawDescOnce.Do(func() {
		file_activex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activex_proto_rawDesc), len(file_activex_proto_rawDesc)))
	})
	return file_activex_proto_rawDescData
}

var file_activex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_activex_proto_goTypes = []any{
	(*ActiveXProperty)(nil),           // 0: synurang.v1.ActiveXProperty
	(*ActiveXServiceOption)(nil),      // 1: synurang.v1.ActiveXServiceOption
	(*descriptor.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
}
var file_activex_proto_depIdxs = []int32{
	0, // 0: synurang.v1.ActiveXServiceOption.properties:type_name -> synurang.v1.ActiveXProperty
	2, // 1: synurang.v1.activex_service:extendee -> google.protobuf.ServiceOptions
	1, // 2: synurang.v1.activex_service:type_name -> synurang.v1.ActiveXServiceOption
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_activex_proto_init() }
func file_activex_proto_init() {
	if File_activex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activex_proto_rawDesc), len(file_activex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_activex_proto_goTypes,
		DependencyIndexes: file_activex_proto_depIdxs,
		MessageInfos:      file_activex_proto_msgTypes,
		ExtensionInfos:    file_activex_proto_extTypes,
	}.Build()
	File_activex_proto = out.File
	file_activex_proto_goTypes = nil
	file_activex_proto_depIdxs = nil
}
