// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.

package api

/*
#include <stdlib.h>
*/
import "C"

import (
	"context"
	"fmt"
	"unsafe"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/emptypb"
)

type FfiServer interface {
	HealthServiceServer
	CacheServiceServer
}

func Invoke(s FfiServer, ctx context.Context, method string, data []byte) ([]byte, error) {
	switch method {
	case "/core.v1.HealthService/Ping":
		req := &emptypb.Empty{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Ping(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/core.v1.CacheService/Get":
		req := &GetCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Get(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/core.v1.CacheService/Put":
		req := &PutCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Put(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/core.v1.CacheService/Delete":
		req := &DeleteCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Delete(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/core.v1.CacheService/Clear":
		req := &ClearCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Clear(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/core.v1.CacheService/Contains":
		req := &GetCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Contains(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/core.v1.CacheService/Keys":
		req := &GetCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Keys(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/core.v1.CacheService/SetMaxEntries":
		req := &SetMaxEntriesRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.SetMaxEntries(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/core.v1.CacheService/SetMaxBytes":
		req := &SetMaxBytesRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.SetMaxBytes(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/core.v1.CacheService/GetStats":
		req := &GetStatsRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.GetStats(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/core.v1.CacheService/Compact":
		req := &emptypb.Empty{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Compact(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	default:
		return nil, fmt.Errorf("unknown method: %s", method)
	}
}

// InvokeFfi is the zero-copy variant for FFI mode.
// It allocates C memory and serializes directly into it.
// Caller is responsible for freeing the returned pointer via C.free().
func InvokeFfi(s FfiServer, ctx context.Context, method string, data []byte) (unsafe.Pointer, int64, error) {
	switch method {
	case "/core.v1.HealthService/Ping":
		req := &emptypb.Empty{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Ping(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	case "/core.v1.CacheService/Get":
		req := &GetCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Get(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	case "/core.v1.CacheService/Put":
		req := &PutCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Put(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	case "/core.v1.CacheService/Delete":
		req := &DeleteCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Delete(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	case "/core.v1.CacheService/Clear":
		req := &ClearCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Clear(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	case "/core.v1.CacheService/Contains":
		req := &GetCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Contains(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	case "/core.v1.CacheService/Keys":
		req := &GetCacheRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Keys(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	case "/core.v1.CacheService/SetMaxEntries":
		req := &SetMaxEntriesRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.SetMaxEntries(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	case "/core.v1.CacheService/SetMaxBytes":
		req := &SetMaxBytesRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.SetMaxBytes(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	case "/core.v1.CacheService/GetStats":
		req := &GetStatsRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.GetStats(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	case "/core.v1.CacheService/Compact":
		req := &emptypb.Empty{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Compact(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	default:
		return nil, 0, fmt.Errorf("unknown method: %s", method)
	}
}
