// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.

package api

/*
#include <stdlib.h>
*/
import "C"

import (
	"context"
	"fmt"
	"unsafe"

	"github.com/ivere27/synurang/pkg/synurang"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
)

// =============================================================================
// HealthService FFI Server Interface
// =============================================================================

type HealthServiceFfiServer interface {
	HealthServiceServer
}

// =============================================================================
// HealthService Invoke - returns []byte (for TCP/UDS)
// =============================================================================

func HealthServiceInvoke(s HealthServiceFfiServer, ctx context.Context, method string, data []byte) ([]byte, error) {
	switch method {
	case "/core.v1.HealthService/Ping":
		req := &empty.Empty{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Ping(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	default:
		return nil, fmt.Errorf("unknown method: %s", method)
	}
}

// =============================================================================
// HealthService InvokeFfi - returns C pointer (for zero-copy FFI)
// =============================================================================

// HealthServiceInvokeFfi is the zero-copy variant for FFI mode.
// It allocates C memory and serializes directly into it.
// Caller is responsible for freeing the returned pointer via C.free().
func HealthServiceInvokeFfi(s HealthServiceFfiServer, ctx context.Context, method string, data []byte) (unsafe.Pointer, int64, error) {
	switch method {
	case "/core.v1.HealthService/Ping":
		req := &empty.Empty{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, 0, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := s.Ping(ctx, req)
		if err != nil {
			return nil, 0, err
		}
		// Zero-copy: allocate C memory and serialize directly
		size := proto.Size(resp)
		if size == 0 {
			return nil, 0, nil
		}
		cPtr := C.malloc(C.size_t(size))
		if cPtr == nil {
			return nil, 0, fmt.Errorf("failed to allocate memory for response")
		}
		buf := unsafe.Slice((*byte)(cPtr), size)
		if _, err := (proto.MarshalOptions{}).MarshalAppend(buf[:0], resp); err != nil {
			C.free(cPtr)
			return nil, 0, err
		}
		return cPtr, int64(size), nil
	default:
		return nil, 0, fmt.Errorf("unknown method: %s", method)
	}
}

// =============================================================================
// HealthService FFI Invoker - wraps HealthServiceFfiServer
// =============================================================================

// healthServiceFfiInvoker wraps HealthServiceFfiServer to implement the synurang.Invoker interface.
// This allows using the synurang runtime's FfiClientConn with generated code.
// Uses zero-copy: proto.Message pointers are passed directly without serialization.
type healthServiceFfiInvoker struct {
	server HealthServiceFfiServer
}

// Invoke implements synurang.UnaryInvoker (zero-copy).
func (i *healthServiceFfiInvoker) Invoke(ctx context.Context, method string, req, reply proto.Message) error {
	switch method {
	case "/core.v1.HealthService/Ping":
		resp, err := i.server.Ping(ctx, req.(*empty.Empty))
		if err != nil {
			return err
		}
		// Use proto.Merge to avoid copying mutex in MessageState
		proto.Merge(reply.(proto.Message), resp)
		return nil
	default:
		return fmt.Errorf("unknown method: %s", method)
	}
}

// InvokeStream implements synurang.StreamInvoker (zero-copy).
func (i *healthServiceFfiInvoker) InvokeStream(ctx context.Context, method string, stream synurang.ServerStream) error {
	switch method {
	default:
		return fmt.Errorf("unknown streaming method: %s", method)
	}
}

var _ synurang.Invoker = (*healthServiceFfiInvoker)(nil)

// =============================================================================
// HealthService FFI Client - convenience wrapper for synurang.FfiClientConn
// =============================================================================

func NewHealthServiceFfiClientConn(server HealthServiceFfiServer) grpc.ClientConnInterface {
	return synurang.NewFfiClientConn(&healthServiceFfiInvoker{server: server})
}
