// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.

package api

/*
#include <stdlib.h>
*/
import "C"

import (
	"context"
	"fmt"
	"unsafe"

	"io"

	"github.com/ivere27/synurang/pkg/ffierror"
	"github.com/ivere27/synurang/pkg/plugin"
	"google.golang.org/protobuf/proto"
)

// trySendErr sends error to channel non-blocking
func trySendErr(ch chan<- error, err error) {
	select {
	case ch <- err:
	default:
	}
}

// =============================================================================
// Plugin Stream Interfaces
// =============================================================================

// GoGreeterService_BarServerStreamPluginStream is the minimal stream surface exposed to FFI plugins.
type GoGreeterService_BarServerStreamPluginStream interface {
	Send(*HelloResponse) error
	Context() context.Context
}

// GoGreeterService_BarClientStreamPluginStream is the minimal stream surface exposed to FFI plugins.
type GoGreeterService_BarClientStreamPluginStream interface {
	Recv() (*HelloRequest, error)
	Context() context.Context
}

// GoGreeterService_BarBidiStreamPluginStream is the minimal stream surface exposed to FFI plugins.
type GoGreeterService_BarBidiStreamPluginStream interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	Context() context.Context
}

// GoGreeterService_UploadFilePluginStream is the minimal stream surface exposed to FFI plugins.
type GoGreeterService_UploadFilePluginStream interface {
	Recv() (*FileChunk, error)
	Context() context.Context
}

// GoGreeterService_DownloadFilePluginStream is the minimal stream surface exposed to FFI plugins.
type GoGreeterService_DownloadFilePluginStream interface {
	Send(*FileChunk) error
	Context() context.Context
}

// GoGreeterService_BidiFilePluginStream is the minimal stream surface exposed to FFI plugins.
type GoGreeterService_BidiFilePluginStream interface {
	Send(*FileChunk) error
	Recv() (*FileChunk, error)
	Context() context.Context
}

// =============================================================================
// Plugin Interfaces and Registration
// =============================================================================

// GoGreeterServicePlugin is the interface that plugin implementations must satisfy.
// Only methods for this specific service are required.
type GoGreeterServicePlugin interface {
	Bar(context.Context, *HelloRequest) (*HelloResponse, error)
	BarServerStream(*HelloRequest, GoGreeterService_BarServerStreamPluginStream) error
	BarClientStream(GoGreeterService_BarClientStreamPluginStream) (*HelloResponse, error)
	BarBidiStream(GoGreeterService_BarBidiStreamPluginStream) error
	UploadFile(GoGreeterService_UploadFilePluginStream) (*FileStatus, error)
	DownloadFile(*DownloadFileRequest, GoGreeterService_DownloadFilePluginStream) error
	BidiFile(GoGreeterService_BidiFilePluginStream) error
	Trigger(context.Context, *TriggerRequest) (*HelloResponse, error)
	GetGoroutines(context.Context, *GoroutinesRequest) (*GoroutinesResponse, error)
}

var pluginGoGreeterService GoGreeterServicePlugin

// RegisterGoGreeterServicePlugin sets the plugin implementation for GoGreeterService.
// This must be called in the plugin's init() function.
func RegisterGoGreeterServicePlugin(s GoGreeterServicePlugin) {
	pluginGoGreeterService = s
}

// =============================================================================
// Internal Invoke Functions (unary methods only)
// =============================================================================

func invokeGoGreeterService(ctx context.Context, method string, data []byte) ([]byte, error) {
	if pluginGoGreeterService == nil {
		return nil, fmt.Errorf("plugin not registered for GoGreeterService")
	}
	switch method {
	case "/example.v1.GoGreeterService/Bar":
		req := &HelloRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := pluginGoGreeterService.Bar(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/example.v1.GoGreeterService/Trigger":
		req := &TriggerRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := pluginGoGreeterService.Trigger(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/example.v1.GoGreeterService/GetGoroutines":
		req := &GoroutinesRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := pluginGoGreeterService.GetGoroutines(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	default:
		return nil, fmt.Errorf("unknown method: %s", method)
	}
}

// =============================================================================
// C-Exported Functions
// =============================================================================

// Response format:
//   success: resp_len >= 0, payload is raw protobuf bytes
//   error:   resp_len < 0, payload is serialized core.v1.Error

//export Synurang_Invoke_GoGreeterService
func Synurang_Invoke_GoGreeterService(method *C.char, data *C.char, dataLen C.int, respLen *C.int) *C.char {
	ctx := context.Background()
	m := C.GoString(method)

	// Handle nil data safely
	var d []byte
	if data != nil && dataLen > 0 {
		d = C.GoBytes(unsafe.Pointer(data), dataLen)
	}

	res, err := invokeGoGreeterService(ctx, m, d)
	if err != nil {
		errBytes := ffierror.Marshal(err)
		*respLen = -C.int(len(errBytes))
		if len(errBytes) == 0 {
			return nil
		}
		return (*C.char)(C.CBytes(errBytes))
	}

	*respLen = C.int(len(res))
	if len(res) == 0 {
		return nil
	}
	return (*C.char)(C.CBytes(res))
}

// =============================================================================
// Streaming Support
// =============================================================================

//export Synurang_Stream_GoGreeterService_Open
func Synurang_Stream_GoGreeterService_Open(method *C.char) C.ulonglong {
	if pluginGoGreeterService == nil {
		return 0
	}

	m := C.GoString(method)
	handle, ps := plugin.NewStream(m)

	// Start stream handler goroutine
	go func() {
		defer close(ps.Done)
		defer ps.CloseRecvCh()
		defer ps.Cancel()

		// Recover from panics in plugin methods
		defer func() {
			if r := recover(); r != nil {
				trySendErr(ps.ErrCh, fmt.Errorf("panic in plugin: %v", r))
			}
		}()

		switch m {
		case "/example.v1.GoGreeterService/BarServerStream":
			// Server streaming - receive initial request, then send responses
			select {
			case data := <-ps.SendCh:
				req := &HelloRequest{}
				if err := proto.Unmarshal(data, req); err != nil {
					trySendErr(ps.ErrCh, err)
					return
				}
				if err := pluginGoGreeterService.BarServerStream(req, &pluginStreamGoGreeterServiceBarServerStream{ps}); err != nil && err != io.EOF {
					trySendErr(ps.ErrCh, err)
				}
			case <-ps.Ctx.Done():
				return
			}
		case "/example.v1.GoGreeterService/BarClientStream":
			// Client streaming
			resp, err := pluginGoGreeterService.BarClientStream(&pluginStreamGoGreeterServiceBarClientStream{ps})
			if err != nil {
				trySendErr(ps.ErrCh, err)
				return
			}
			if data, err := proto.Marshal(resp); err != nil {
				trySendErr(ps.ErrCh, err)
			} else {
				select {
				case ps.RecvCh <- data:
				case <-ps.Ctx.Done():
				}
			}
		case "/example.v1.GoGreeterService/BarBidiStream":
			// Bidi streaming
			if err := pluginGoGreeterService.BarBidiStream(&pluginStreamGoGreeterServiceBarBidiStream{ps}); err != nil && err != io.EOF {
				trySendErr(ps.ErrCh, err)
			}
		case "/example.v1.GoGreeterService/UploadFile":
			// Client streaming
			resp, err := pluginGoGreeterService.UploadFile(&pluginStreamGoGreeterServiceUploadFile{ps})
			if err != nil {
				trySendErr(ps.ErrCh, err)
				return
			}
			if data, err := proto.Marshal(resp); err != nil {
				trySendErr(ps.ErrCh, err)
			} else {
				select {
				case ps.RecvCh <- data:
				case <-ps.Ctx.Done():
				}
			}
		case "/example.v1.GoGreeterService/DownloadFile":
			// Server streaming - receive initial request, then send responses
			select {
			case data := <-ps.SendCh:
				req := &DownloadFileRequest{}
				if err := proto.Unmarshal(data, req); err != nil {
					trySendErr(ps.ErrCh, err)
					return
				}
				if err := pluginGoGreeterService.DownloadFile(req, &pluginStreamGoGreeterServiceDownloadFile{ps}); err != nil && err != io.EOF {
					trySendErr(ps.ErrCh, err)
				}
			case <-ps.Ctx.Done():
				return
			}
		case "/example.v1.GoGreeterService/BidiFile":
			// Bidi streaming
			if err := pluginGoGreeterService.BidiFile(&pluginStreamGoGreeterServiceBidiFile{ps}); err != nil && err != io.EOF {
				trySendErr(ps.ErrCh, err)
			}
		}
	}()

	return C.ulonglong(handle)
}

// =============================================================================
// Plugin Stream Wrappers
// =============================================================================

type pluginStreamGoGreeterServiceBarServerStream struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceBarServerStream) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceBarServerStream) Send(m *HelloResponse) error {
	data, err := proto.Marshal(m)
	if err != nil {
		return err
	}
	select {
	case s.ps.RecvCh <- data:
		return nil
	case <-s.ps.Ctx.Done():
		return s.ps.Ctx.Err()
	}
}

var _ GoGreeterService_BarServerStreamPluginStream = (*pluginStreamGoGreeterServiceBarServerStream)(nil)

type pluginStreamGoGreeterServiceBarClientStream struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceBarClientStream) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceBarClientStream) Recv() (*HelloRequest, error) {
	select {
	case data, ok := <-s.ps.SendCh:
		if !ok {
			return nil, io.EOF
		}
		req := &HelloRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, err
		}
		return req, nil
	case <-s.ps.Ctx.Done():
		return nil, s.ps.Ctx.Err()
	}
}

var _ GoGreeterService_BarClientStreamPluginStream = (*pluginStreamGoGreeterServiceBarClientStream)(nil)

type pluginStreamGoGreeterServiceBarBidiStream struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceBarBidiStream) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceBarBidiStream) Send(m *HelloResponse) error {
	data, err := proto.Marshal(m)
	if err != nil {
		return err
	}
	select {
	case s.ps.RecvCh <- data:
		return nil
	case <-s.ps.Ctx.Done():
		return s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceBarBidiStream) Recv() (*HelloRequest, error) {
	select {
	case data, ok := <-s.ps.SendCh:
		if !ok {
			return nil, io.EOF
		}
		req := &HelloRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, err
		}
		return req, nil
	case <-s.ps.Ctx.Done():
		return nil, s.ps.Ctx.Err()
	}
}

var _ GoGreeterService_BarBidiStreamPluginStream = (*pluginStreamGoGreeterServiceBarBidiStream)(nil)

type pluginStreamGoGreeterServiceUploadFile struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceUploadFile) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceUploadFile) Recv() (*FileChunk, error) {
	select {
	case data, ok := <-s.ps.SendCh:
		if !ok {
			return nil, io.EOF
		}
		req := &FileChunk{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, err
		}
		return req, nil
	case <-s.ps.Ctx.Done():
		return nil, s.ps.Ctx.Err()
	}
}

var _ GoGreeterService_UploadFilePluginStream = (*pluginStreamGoGreeterServiceUploadFile)(nil)

type pluginStreamGoGreeterServiceDownloadFile struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceDownloadFile) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceDownloadFile) Send(m *FileChunk) error {
	data, err := proto.Marshal(m)
	if err != nil {
		return err
	}
	select {
	case s.ps.RecvCh <- data:
		return nil
	case <-s.ps.Ctx.Done():
		return s.ps.Ctx.Err()
	}
}

var _ GoGreeterService_DownloadFilePluginStream = (*pluginStreamGoGreeterServiceDownloadFile)(nil)

type pluginStreamGoGreeterServiceBidiFile struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceBidiFile) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceBidiFile) Send(m *FileChunk) error {
	data, err := proto.Marshal(m)
	if err != nil {
		return err
	}
	select {
	case s.ps.RecvCh <- data:
		return nil
	case <-s.ps.Ctx.Done():
		return s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceBidiFile) Recv() (*FileChunk, error) {
	select {
	case data, ok := <-s.ps.SendCh:
		if !ok {
			return nil, io.EOF
		}
		req := &FileChunk{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, err
		}
		return req, nil
	case <-s.ps.Ctx.Done():
		return nil, s.ps.Ctx.Err()
	}
}

var _ GoGreeterService_BidiFilePluginStream = (*pluginStreamGoGreeterServiceBidiFile)(nil)
