// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.

package api

/*
#include <stdlib.h>
*/
import "C"

import (
	"context"
	"fmt"
	"unsafe"

	"github.com/ivere27/synurang/pkg/plugin"
	"google.golang.org/protobuf/proto"
)

import (
	"io"

	"google.golang.org/grpc/metadata"
)

// trySendErr sends error to channel non-blocking
func trySendErr(ch chan<- error, err error) {
	select {
	case ch <- err:
	default:
	}
}

// GoGreeterServicePlugin is the interface that plugin implementations must satisfy.
// Only methods for this specific service are required.
type GoGreeterServicePlugin interface {
	Bar(context.Context, *HelloRequest) (*HelloResponse, error)
	BarServerStream(*HelloRequest, GoGreeterService_BarServerStreamServer) error
	BarClientStream(GoGreeterService_BarClientStreamServer) (*HelloResponse, error)
	BarBidiStream(GoGreeterService_BarBidiStreamServer) error
	UploadFile(GoGreeterService_UploadFileServer) (*FileStatus, error)
	DownloadFile(*DownloadFileRequest, GoGreeterService_DownloadFileServer) error
	BidiFile(GoGreeterService_BidiFileServer) error
	Trigger(context.Context, *TriggerRequest) (*HelloResponse, error)
	GetGoroutines(context.Context, *GoroutinesRequest) (*GoroutinesResponse, error)
}

var pluginGoGreeterService GoGreeterServicePlugin

// RegisterGoGreeterServicePlugin sets the plugin implementation for GoGreeterService.
// This must be called in the plugin's init() function.
func RegisterGoGreeterServicePlugin(s GoGreeterServicePlugin) {
	pluginGoGreeterService = s
}

func invokeGoGreeterService(ctx context.Context, method string, data []byte) ([]byte, error) {
	if pluginGoGreeterService == nil {
		return nil, fmt.Errorf("plugin not registered for GoGreeterService")
	}
	switch method {
	case "/example.v1.GoGreeterService/Bar":
		req := &HelloRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := pluginGoGreeterService.Bar(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/example.v1.GoGreeterService/Trigger":
		req := &TriggerRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := pluginGoGreeterService.Trigger(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	case "/example.v1.GoGreeterService/GetGoroutines":
		req := &GoroutinesRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, fmt.Errorf("failed to unmarshal request: %w", err)
		}
		resp, err := pluginGoGreeterService.GetGoroutines(ctx, req)
		if err != nil {
			return nil, err
		}
		return proto.Marshal(resp)
	default:
		return nil, fmt.Errorf("unknown method: %s", method)
	}
}

// =============================================================================
// C-Exported Functions
// =============================================================================

// Response format: [status:1][payload...]
// status=0: success, payload=protobuf response
// status=1: error, payload=error string

//export Synurang_Invoke_GoGreeterService
func Synurang_Invoke_GoGreeterService(method *C.char, data *C.char, dataLen C.int, respLen *C.int) *C.char {
	ctx := context.Background()
	m := C.GoString(method)

	// Handle nil data safely
	var d []byte
	if data != nil && dataLen > 0 {
		d = C.GoBytes(unsafe.Pointer(data), dataLen)
	}

	res, err := invokeGoGreeterService(ctx, m, d)
	if err != nil {
		// Return error with status byte = 1
		errBytes := []byte(err.Error())
		result := make([]byte, 1+len(errBytes))
		result[0] = 1 // error status
		copy(result[1:], errBytes)
		*respLen = C.int(len(result))
		return (*C.char)(C.CBytes(result))
	}

	// Return success with status byte = 0
	result := make([]byte, 1+len(res))
	result[0] = 0 // success status
	copy(result[1:], res)
	*respLen = C.int(len(result))
	return (*C.char)(C.CBytes(result))
}

// =============================================================================
// Streaming Support
// =============================================================================

//export Synurang_Stream_GoGreeterService_Open
func Synurang_Stream_GoGreeterService_Open(method *C.char) C.ulonglong {
	if pluginGoGreeterService == nil {
		return 0
	}

	m := C.GoString(method)
	handle, ps := plugin.NewStream(m)

	// Start stream handler goroutine
	go func() {
		defer ps.CloseRecvCh()
		defer ps.Cancel()

		// Recover from panics in plugin methods
		defer func() {
			if r := recover(); r != nil {
				trySendErr(ps.ErrCh, fmt.Errorf("panic in plugin: %v", r))
			}
		}()

		switch m {
		case "/example.v1.GoGreeterService/BarServerStream":
			// Server streaming - receive initial request, then send responses
			select {
			case data := <-ps.SendCh:
				req := &HelloRequest{}
				if err := proto.Unmarshal(data, req); err != nil {
					trySendErr(ps.ErrCh, err)
					return
				}
				if err := pluginGoGreeterService.BarServerStream(req, &pluginStreamGoGreeterServiceBarServerStream{ps}); err != nil && err != io.EOF {
					trySendErr(ps.ErrCh, err)
				}
			case <-ps.Ctx.Done():
				return
			}
		case "/example.v1.GoGreeterService/BarClientStream":
			// Client streaming
			resp, err := pluginGoGreeterService.BarClientStream(&pluginStreamGoGreeterServiceBarClientStream{ps})
			if err != nil {
				trySendErr(ps.ErrCh, err)
				return
			}
			if data, err := proto.Marshal(resp); err != nil {
				trySendErr(ps.ErrCh, err)
			} else {
				select {
				case ps.RecvCh <- data:
				case <-ps.Ctx.Done():
				}
			}
		case "/example.v1.GoGreeterService/BarBidiStream":
			// Bidi streaming
			if err := pluginGoGreeterService.BarBidiStream(&pluginStreamGoGreeterServiceBarBidiStream{ps}); err != nil && err != io.EOF {
				trySendErr(ps.ErrCh, err)
			}
		case "/example.v1.GoGreeterService/UploadFile":
			// Client streaming
			resp, err := pluginGoGreeterService.UploadFile(&pluginStreamGoGreeterServiceUploadFile{ps})
			if err != nil {
				trySendErr(ps.ErrCh, err)
				return
			}
			if data, err := proto.Marshal(resp); err != nil {
				trySendErr(ps.ErrCh, err)
			} else {
				select {
				case ps.RecvCh <- data:
				case <-ps.Ctx.Done():
				}
			}
		case "/example.v1.GoGreeterService/DownloadFile":
			// Server streaming - receive initial request, then send responses
			select {
			case data := <-ps.SendCh:
				req := &DownloadFileRequest{}
				if err := proto.Unmarshal(data, req); err != nil {
					trySendErr(ps.ErrCh, err)
					return
				}
				if err := pluginGoGreeterService.DownloadFile(req, &pluginStreamGoGreeterServiceDownloadFile{ps}); err != nil && err != io.EOF {
					trySendErr(ps.ErrCh, err)
				}
			case <-ps.Ctx.Done():
				return
			}
		case "/example.v1.GoGreeterService/BidiFile":
			// Bidi streaming
			if err := pluginGoGreeterService.BidiFile(&pluginStreamGoGreeterServiceBidiFile{ps}); err != nil && err != io.EOF {
				trySendErr(ps.ErrCh, err)
			}
		}
	}()

	return C.ulonglong(handle)
}

type pluginStreamGoGreeterServiceBarServerStream struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceBarServerStream) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceBarServerStream) Send(m *HelloResponse) error {
	data, err := proto.Marshal(m)
	if err != nil {
		return err
	}
	select {
	case s.ps.RecvCh <- data:
		return nil
	case <-s.ps.Ctx.Done():
		return s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceBarServerStream) SetHeader(metadata.MD) error  { return nil }
func (s *pluginStreamGoGreeterServiceBarServerStream) SendHeader(metadata.MD) error { return nil }
func (s *pluginStreamGoGreeterServiceBarServerStream) SetTrailer(metadata.MD)       {}
func (s *pluginStreamGoGreeterServiceBarServerStream) SendMsg(m any) error          { return nil }
func (s *pluginStreamGoGreeterServiceBarServerStream) RecvMsg(m any) error          { return nil }

type pluginStreamGoGreeterServiceBarClientStream struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceBarClientStream) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceBarClientStream) Recv() (*HelloRequest, error) {
	select {
	case data, ok := <-s.ps.SendCh:
		if !ok {
			return nil, io.EOF
		}
		req := &HelloRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, err
		}
		return req, nil
	case <-s.ps.Ctx.Done():
		return nil, s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceBarClientStream) SendAndClose(m *HelloResponse) error {
	data, err := proto.Marshal(m)
	if err != nil {
		return err
	}
	select {
	case s.ps.RecvCh <- data:
		return nil
	case <-s.ps.Ctx.Done():
		return s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceBarClientStream) SetHeader(metadata.MD) error  { return nil }
func (s *pluginStreamGoGreeterServiceBarClientStream) SendHeader(metadata.MD) error { return nil }
func (s *pluginStreamGoGreeterServiceBarClientStream) SetTrailer(metadata.MD)       {}
func (s *pluginStreamGoGreeterServiceBarClientStream) SendMsg(m any) error          { return nil }
func (s *pluginStreamGoGreeterServiceBarClientStream) RecvMsg(m any) error          { return nil }

type pluginStreamGoGreeterServiceBarBidiStream struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceBarBidiStream) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceBarBidiStream) Send(m *HelloResponse) error {
	data, err := proto.Marshal(m)
	if err != nil {
		return err
	}
	select {
	case s.ps.RecvCh <- data:
		return nil
	case <-s.ps.Ctx.Done():
		return s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceBarBidiStream) Recv() (*HelloRequest, error) {
	select {
	case data, ok := <-s.ps.SendCh:
		if !ok {
			return nil, io.EOF
		}
		req := &HelloRequest{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, err
		}
		return req, nil
	case <-s.ps.Ctx.Done():
		return nil, s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceBarBidiStream) SetHeader(metadata.MD) error  { return nil }
func (s *pluginStreamGoGreeterServiceBarBidiStream) SendHeader(metadata.MD) error { return nil }
func (s *pluginStreamGoGreeterServiceBarBidiStream) SetTrailer(metadata.MD)       {}
func (s *pluginStreamGoGreeterServiceBarBidiStream) SendMsg(m any) error          { return nil }
func (s *pluginStreamGoGreeterServiceBarBidiStream) RecvMsg(m any) error          { return nil }

type pluginStreamGoGreeterServiceUploadFile struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceUploadFile) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceUploadFile) Recv() (*FileChunk, error) {
	select {
	case data, ok := <-s.ps.SendCh:
		if !ok {
			return nil, io.EOF
		}
		req := &FileChunk{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, err
		}
		return req, nil
	case <-s.ps.Ctx.Done():
		return nil, s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceUploadFile) SendAndClose(m *FileStatus) error {
	data, err := proto.Marshal(m)
	if err != nil {
		return err
	}
	select {
	case s.ps.RecvCh <- data:
		return nil
	case <-s.ps.Ctx.Done():
		return s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceUploadFile) SetHeader(metadata.MD) error  { return nil }
func (s *pluginStreamGoGreeterServiceUploadFile) SendHeader(metadata.MD) error { return nil }
func (s *pluginStreamGoGreeterServiceUploadFile) SetTrailer(metadata.MD)       {}
func (s *pluginStreamGoGreeterServiceUploadFile) SendMsg(m any) error          { return nil }
func (s *pluginStreamGoGreeterServiceUploadFile) RecvMsg(m any) error          { return nil }

type pluginStreamGoGreeterServiceDownloadFile struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceDownloadFile) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceDownloadFile) Send(m *FileChunk) error {
	data, err := proto.Marshal(m)
	if err != nil {
		return err
	}
	select {
	case s.ps.RecvCh <- data:
		return nil
	case <-s.ps.Ctx.Done():
		return s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceDownloadFile) SetHeader(metadata.MD) error  { return nil }
func (s *pluginStreamGoGreeterServiceDownloadFile) SendHeader(metadata.MD) error { return nil }
func (s *pluginStreamGoGreeterServiceDownloadFile) SetTrailer(metadata.MD)       {}
func (s *pluginStreamGoGreeterServiceDownloadFile) SendMsg(m any) error          { return nil }
func (s *pluginStreamGoGreeterServiceDownloadFile) RecvMsg(m any) error          { return nil }

type pluginStreamGoGreeterServiceBidiFile struct {
	ps *plugin.PluginStream
}

func (s *pluginStreamGoGreeterServiceBidiFile) Context() context.Context {
	return s.ps.Ctx
}

func (s *pluginStreamGoGreeterServiceBidiFile) Send(m *FileChunk) error {
	data, err := proto.Marshal(m)
	if err != nil {
		return err
	}
	select {
	case s.ps.RecvCh <- data:
		return nil
	case <-s.ps.Ctx.Done():
		return s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceBidiFile) Recv() (*FileChunk, error) {
	select {
	case data, ok := <-s.ps.SendCh:
		if !ok {
			return nil, io.EOF
		}
		req := &FileChunk{}
		if err := proto.Unmarshal(data, req); err != nil {
			return nil, err
		}
		return req, nil
	case <-s.ps.Ctx.Done():
		return nil, s.ps.Ctx.Err()
	}
}

func (s *pluginStreamGoGreeterServiceBidiFile) SetHeader(metadata.MD) error  { return nil }
func (s *pluginStreamGoGreeterServiceBidiFile) SendHeader(metadata.MD) error { return nil }
func (s *pluginStreamGoGreeterServiceBidiFile) SetTrailer(metadata.MD)       {}
func (s *pluginStreamGoGreeterServiceBidiFile) SendMsg(m any) error          { return nil }
func (s *pluginStreamGoGreeterServiceBidiFile) RecvMsg(m any) error          { return nil }
