// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.

import 'dart:async';
import 'dart:typed_data';
import 'package:synurang/synurang.dart' as synurang;
import 'example.pb.dart';

class GoGreeterServiceFfi {
  static Future<HelloResponse> Bar(HelloRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/example.v1.GoGreeterService/Bar', bytes);
    return HelloResponse.fromBuffer(resultBytes);
  }

  static Stream<HelloResponse> BarServerStream(HelloRequest request) {
    final bytes = request.writeToBuffer();
    return synurang.invokeBackendServerStream('/example.v1.GoGreeterService/BarServerStream', bytes)
        .map((data) => HelloResponse.fromBuffer(data));
  }

  static Future<HelloResponse> BarClientStream(Stream<HelloRequest> requests) async {
    final resultBytes = await synurang.invokeBackendClientStream('/example.v1.GoGreeterService/BarClientStream',
        requests.map((r) => r.writeToBuffer()));
    return HelloResponse.fromBuffer(resultBytes);
  }

  static Stream<HelloResponse> BarBidiStream(Stream<HelloRequest> requests) {
    return synurang.invokeBackendBidiStream('/example.v1.GoGreeterService/BarBidiStream',
        requests.map((r) => r.writeToBuffer()))
        .map((data) => HelloResponse.fromBuffer(data));
  }

  static Future<FileStatus> UploadFile(Stream<FileChunk> requests) async {
    final resultBytes = await synurang.invokeBackendClientStream('/example.v1.GoGreeterService/UploadFile',
        requests.map((r) => r.writeToBuffer()));
    return FileStatus.fromBuffer(resultBytes);
  }

  static Stream<FileChunk> DownloadFile(DownloadFileRequest request) {
    final bytes = request.writeToBuffer();
    return synurang.invokeBackendServerStream('/example.v1.GoGreeterService/DownloadFile', bytes)
        .map((data) => FileChunk.fromBuffer(data));
  }

  static Stream<FileChunk> BidiFile(Stream<FileChunk> requests) {
    return synurang.invokeBackendBidiStream('/example.v1.GoGreeterService/BidiFile',
        requests.map((r) => r.writeToBuffer()))
        .map((data) => FileChunk.fromBuffer(data));
  }

  static Future<HelloResponse> Trigger(TriggerRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/example.v1.GoGreeterService/Trigger', bytes);
    return HelloResponse.fromBuffer(resultBytes);
  }

  static Future<GoroutinesResponse> GetGoroutines(GoroutinesRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/example.v1.GoGreeterService/GetGoroutines', bytes);
    return GoroutinesResponse.fromBuffer(resultBytes);
  }

}

