// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: example.proto

package api

import (
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	api "github.com/ivere27/synurang/pkg/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerRequest_Action int32

const (
	TriggerRequest_UNARY         TriggerRequest_Action = 0
	TriggerRequest_SERVER_STREAM TriggerRequest_Action = 1
	TriggerRequest_CLIENT_STREAM TriggerRequest_Action = 2
	TriggerRequest_BIDI_STREAM   TriggerRequest_Action = 3
	TriggerRequest_UPLOAD_FILE   TriggerRequest_Action = 4
	TriggerRequest_DOWNLOAD_FILE TriggerRequest_Action = 5
	TriggerRequest_BIDI_FILE     TriggerRequest_Action = 6
)

// Enum value maps for TriggerRequest_Action.
var (
	TriggerRequest_Action_name = map[int32]string{
		0: "UNARY",
		1: "SERVER_STREAM",
		2: "CLIENT_STREAM",
		3: "BIDI_STREAM",
		4: "UPLOAD_FILE",
		5: "DOWNLOAD_FILE",
		6: "BIDI_FILE",
	}
	TriggerRequest_Action_value = map[string]int32{
		"UNARY":         0,
		"SERVER_STREAM": 1,
		"CLIENT_STREAM": 2,
		"BIDI_STREAM":   3,
		"UPLOAD_FILE":   4,
		"DOWNLOAD_FILE": 5,
		"BIDI_FILE":     6,
	}
)

func (x TriggerRequest_Action) Enum() *TriggerRequest_Action {
	p := new(TriggerRequest_Action)
	*p = x
	return p
}

func (x TriggerRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[0].Descriptor()
}

func (TriggerRequest_Action) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[0]
}

func (x TriggerRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerRequest_Action.Descriptor instead.
func (TriggerRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{4, 0}
}

// =============================================================================
// Messages
// =============================================================================
type GoroutinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsString      bool                   `protobuf:"varint,1,opt,name=as_string,json=asString,proto3" json:"as_string,omitempty"` // If true, return full stack trace in message field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoroutinesRequest) Reset() {
	*x = GoroutinesRequest{}
	mi := &file_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoroutinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoroutinesRequest) ProtoMessage() {}

func (x *GoroutinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoroutinesRequest.ProtoReflect.Descriptor instead.
func (*GoroutinesRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *GoroutinesRequest) GetAsString() bool {
	if x != nil {
		return x.AsString
	}
	return false
}

type GoroutinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional: contains stack trace if requested
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoroutinesResponse) Reset() {
	*x = GoroutinesResponse{}
	mi := &file_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoroutinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoroutinesResponse) ProtoMessage() {}

func (x *GoroutinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoroutinesResponse.ProtoReflect.Descriptor instead.
func (*GoroutinesResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *GoroutinesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GoroutinesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // Optional: "en", "ko", "ja", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{2}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"` // "go" or "dart" - identifies which server responded
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{3}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *HelloResponse) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TriggerRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Action  TriggerRequest_Action  `protobuf:"varint,1,opt,name=action,proto3,enum=example.v1.TriggerRequest_Action" json:"action,omitempty"`
	Payload *HelloRequest          `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// For file tests, we might want to pass file size/seed via payload or separate field
	// For now, let's just reuse payload.Name as seed/size param or add dedicated fields if needed.
	FileSize      int64 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerRequest) GetAction() TriggerRequest_Action {
	if x != nil {
		return x.Action
	}
	return TriggerRequest_UNARY
}

func (x *TriggerRequest) GetPayload() *HelloRequest {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TriggerRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{5}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FileStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeReceived  int64                  `protobuf:"varint,1,opt,name=size_received,json=sizeReceived,proto3" json:"size_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStatus) Reset() {
	*x = FileStatus{}
	mi := &file_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatus) ProtoMessage() {}

func (x *FileStatus) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatus.ProtoReflect.Descriptor instead.
func (*FileStatus) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{6}
}

func (x *FileStatus) GetSizeReceived() int64 {
	if x != nil {
		return x.SizeReceived
	}
	return 0
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{7}
}

func (x *FileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"` // Seed removed as we want true random
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_example_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// =============================================================================
// Cross-proto import test message
// These messages use types from core.proto to verify proto imports work
// =============================================================================
type CrossProtoTestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to core.v1.Error from core.proto
	Error *api.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Reference to core.v1.PingResponse from core.proto
	PingResponse *api.PingResponse `protobuf:"bytes,2,opt,name=ping_response,json=pingResponse,proto3" json:"ping_response,omitempty"`
	// Local field
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossProtoTestMessage) Reset() {
	*x = CrossProtoTestMessage{}
	mi := &file_example_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossProtoTestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossProtoTestMessage) ProtoMessage() {}

func (x *CrossProtoTestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossProtoTestMessage.ProtoReflect.Descriptor instead.
func (*CrossProtoTestMessage) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{9}
}

func (x *CrossProtoTestMessage) GetError() *api.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CrossProtoTestMessage) GetPingResponse() *api.PingResponse {
	if x != nil {
		return x.PingResponse
	}
	return nil
}

func (x *CrossProtoTestMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_example_proto protoreflect.FileDescriptor

const file_example_proto_rawDesc = "" +
	"\n" +
	"\rexample.proto\x12\n" +
	"example.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\n" +
	"core.proto\"0\n" +
	"\x11GoroutinesRequest\x12\x1b\n" +
	"\tas_string\x18\x01 \x01(\bR\basString\"D\n" +
	"\x12GoroutinesResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"w\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x9b\x02\n" +
	"\x0eTriggerRequest\x129\n" +
	"\x06action\x18\x01 \x01(\x0e2!.example.v1.TriggerRequest.ActionR\x06action\x122\n" +
	"\apayload\x18\x02 \x01(\v2\x18.example.v1.HelloRequestR\apayload\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\"}\n" +
	"\x06Action\x12\t\n" +
	"\x05UNARY\x10\x00\x12\x11\n" +
	"\rSERVER_STREAM\x10\x01\x12\x11\n" +
	"\rCLIENT_STREAM\x10\x02\x12\x0f\n" +
	"\vBIDI_STREAM\x10\x03\x12\x0f\n" +
	"\vUPLOAD_FILE\x10\x04\x12\x11\n" +
	"\rDOWNLOAD_FILE\x10\x05\x12\r\n" +
	"\tBIDI_FILE\x10\x06\"%\n" +
	"\tFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"1\n" +
	"\n" +
	"FileStatus\x12#\n" +
	"\rsize_received\x18\x01 \x01(\x03R\fsizeReceived\"!\n" +
	"\vFileRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\")\n" +
	"\x13DownloadFileRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\"\x9b\x01\n" +
	"\x15CrossProtoTestMessage\x12$\n" +
	"\x05error\x18\x01 \x01(\v2\x0e.core.v1.ErrorR\x05error\x12:\n" +
	"\rping_response\x18\x02 \x01(\v2\x15.core.v1.PingResponseR\fpingResponse\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription2\x85\x05\n" +
	"\x10GoGreeterService\x12:\n" +
	"\x03Bar\x12\x18.example.v1.HelloRequest\x1a\x19.example.v1.HelloResponse\x12H\n" +
	"\x0fBarServerStream\x12\x18.example.v1.HelloRequest\x1a\x19.example.v1.HelloResponse0\x01\x12H\n" +
	"\x0fBarClientStream\x12\x18.example.v1.HelloRequest\x1a\x19.example.v1.HelloResponse(\x01\x12H\n" +
	"\rBarBidiStream\x12\x18.example.v1.HelloRequest\x1a\x19.example.v1.HelloResponse(\x010\x01\x12=\n" +
	"\n" +
	"UploadFile\x12\x15.example.v1.FileChunk\x1a\x16.example.v1.FileStatus(\x01\x12H\n" +
	"\fDownloadFile\x12\x1f.example.v1.DownloadFileRequest\x1a\x15.example.v1.FileChunk0\x01\x12<\n" +
	"\bBidiFile\x12\x15.example.v1.FileChunk\x1a\x15.example.v1.FileChunk(\x010\x01\x12@\n" +
	"\aTrigger\x12\x1a.example.v1.TriggerRequest\x1a\x19.example.v1.HelloResponse\x12N\n" +
	"\rGetGoroutines\x12\x1d.example.v1.GoroutinesRequest\x1a\x1e.example.v1.GoroutinesResponse2\x81\x04\n" +
	"\x12DartGreeterService\x12:\n" +
	"\x03Foo\x12\x18.example.v1.HelloRequest\x1a\x19.example.v1.HelloResponse\x12H\n" +
	"\x0fFooServerStream\x12\x18.example.v1.HelloRequest\x1a\x19.example.v1.HelloResponse0\x01\x12H\n" +
	"\x0fFooClientStream\x12\x18.example.v1.HelloRequest\x1a\x19.example.v1.HelloResponse(\x01\x12H\n" +
	"\rFooBidiStream\x12\x18.example.v1.HelloRequest\x1a\x19.example.v1.HelloResponse(\x010\x01\x12A\n" +
	"\x0eDartUploadFile\x12\x15.example.v1.FileChunk\x1a\x16.example.v1.FileStatus(\x01\x12L\n" +
	"\x10DartDownloadFile\x12\x1f.example.v1.DownloadFileRequest\x1a\x15.example.v1.FileChunk0\x01\x12@\n" +
	"\fDartBidiFile\x12\x15.example.v1.FileChunk\x1a\x15.example.v1.FileChunk(\x010\x01B-Z+github.com/ivere27/synurang/example/pkg/apib\x06proto3"

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData []byte
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)))
	})
	return file_example_proto_rawDescData
}

var file_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_example_proto_goTypes = []any{
	(TriggerRequest_Action)(0),    // 0: example.v1.TriggerRequest.Action
	(*GoroutinesRequest)(nil),     // 1: example.v1.GoroutinesRequest
	(*GoroutinesResponse)(nil),    // 2: example.v1.GoroutinesResponse
	(*HelloRequest)(nil),          // 3: example.v1.HelloRequest
	(*HelloResponse)(nil),         // 4: example.v1.HelloResponse
	(*TriggerRequest)(nil),        // 5: example.v1.TriggerRequest
	(*FileChunk)(nil),             // 6: example.v1.FileChunk
	(*FileStatus)(nil),            // 7: example.v1.FileStatus
	(*FileRequest)(nil),           // 8: example.v1.FileRequest
	(*DownloadFileRequest)(nil),   // 9: example.v1.DownloadFileRequest
	(*CrossProtoTestMessage)(nil), // 10: example.v1.CrossProtoTestMessage
	(*timestamp.Timestamp)(nil),   // 11: google.protobuf.Timestamp
	(*api.Error)(nil),             // 12: core.v1.Error
	(*api.PingResponse)(nil),      // 13: core.v1.PingResponse
}
var file_example_proto_depIdxs = []int32{
	11, // 0: example.v1.HelloResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: example.v1.TriggerRequest.action:type_name -> example.v1.TriggerRequest.Action
	3,  // 2: example.v1.TriggerRequest.payload:type_name -> example.v1.HelloRequest
	12, // 3: example.v1.CrossProtoTestMessage.error:type_name -> core.v1.Error
	13, // 4: example.v1.CrossProtoTestMessage.ping_response:type_name -> core.v1.PingResponse
	3,  // 5: example.v1.GoGreeterService.Bar:input_type -> example.v1.HelloRequest
	3,  // 6: example.v1.GoGreeterService.BarServerStream:input_type -> example.v1.HelloRequest
	3,  // 7: example.v1.GoGreeterService.BarClientStream:input_type -> example.v1.HelloRequest
	3,  // 8: example.v1.GoGreeterService.BarBidiStream:input_type -> example.v1.HelloRequest
	6,  // 9: example.v1.GoGreeterService.UploadFile:input_type -> example.v1.FileChunk
	9,  // 10: example.v1.GoGreeterService.DownloadFile:input_type -> example.v1.DownloadFileRequest
	6,  // 11: example.v1.GoGreeterService.BidiFile:input_type -> example.v1.FileChunk
	5,  // 12: example.v1.GoGreeterService.Trigger:input_type -> example.v1.TriggerRequest
	1,  // 13: example.v1.GoGreeterService.GetGoroutines:input_type -> example.v1.GoroutinesRequest
	3,  // 14: example.v1.DartGreeterService.Foo:input_type -> example.v1.HelloRequest
	3,  // 15: example.v1.DartGreeterService.FooServerStream:input_type -> example.v1.HelloRequest
	3,  // 16: example.v1.DartGreeterService.FooClientStream:input_type -> example.v1.HelloRequest
	3,  // 17: example.v1.DartGreeterService.FooBidiStream:input_type -> example.v1.HelloRequest
	6,  // 18: example.v1.DartGreeterService.DartUploadFile:input_type -> example.v1.FileChunk
	9,  // 19: example.v1.DartGreeterService.DartDownloadFile:input_type -> example.v1.DownloadFileRequest
	6,  // 20: example.v1.DartGreeterService.DartBidiFile:input_type -> example.v1.FileChunk
	4,  // 21: example.v1.GoGreeterService.Bar:output_type -> example.v1.HelloResponse
	4,  // 22: example.v1.GoGreeterService.BarServerStream:output_type -> example.v1.HelloResponse
	4,  // 23: example.v1.GoGreeterService.BarClientStream:output_type -> example.v1.HelloResponse
	4,  // 24: example.v1.GoGreeterService.BarBidiStream:output_type -> example.v1.HelloResponse
	7,  // 25: example.v1.GoGreeterService.UploadFile:output_type -> example.v1.FileStatus
	6,  // 26: example.v1.GoGreeterService.DownloadFile:output_type -> example.v1.FileChunk
	6,  // 27: example.v1.GoGreeterService.BidiFile:output_type -> example.v1.FileChunk
	4,  // 28: example.v1.GoGreeterService.Trigger:output_type -> example.v1.HelloResponse
	2,  // 29: example.v1.GoGreeterService.GetGoroutines:output_type -> example.v1.GoroutinesResponse
	4,  // 30: example.v1.DartGreeterService.Foo:output_type -> example.v1.HelloResponse
	4,  // 31: example.v1.DartGreeterService.FooServerStream:output_type -> example.v1.HelloResponse
	4,  // 32: example.v1.DartGreeterService.FooClientStream:output_type -> example.v1.HelloResponse
	4,  // 33: example.v1.DartGreeterService.FooBidiStream:output_type -> example.v1.HelloResponse
	7,  // 34: example.v1.DartGreeterService.DartUploadFile:output_type -> example.v1.FileStatus
	6,  // 35: example.v1.DartGreeterService.DartDownloadFile:output_type -> example.v1.FileChunk
	6,  // 36: example.v1.DartGreeterService.DartBidiFile:output_type -> example.v1.FileChunk
	21, // [21:37] is the sub-list for method output_type
	5,  // [5:21] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		EnumInfos:         file_example_proto_enumTypes,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
