<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>CSharpHostTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../csharp/Synurang/Synurang.csproj" />
  </ItemGroup>

</Project>
