// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.
// C++ Plugin Server Header for Synurang FFI

#ifndef EXAMPLE_FFI_H_
#define EXAMPLE_FFI_H_

#include <cstdint>
#include <cstdlib>
#include <functional>
#include <memory>
#include <mutex>
#include <condition_variable>
#include <queue>
#include <thread>
#include <unordered_map>
#include <string>
#include <vector>

#include "example.pb.h"
#include "google/protobuf/timestamp.pb.h"


namespace example::v1 {


// =============================================================================
// Structured FFI Error
// =============================================================================

class FfiError : public std::runtime_error {
public:
    explicit FfiError(const std::string& message, int32_t code = 0, int32_t grpc_code = 2)
        : std::runtime_error(message), code_(code), grpc_code_(grpc_code) {}

    int32_t code() const noexcept { return code_; }
    int32_t grpc_code() const noexcept { return grpc_code_; }

private:
    int32_t code_;
    int32_t grpc_code_;
};

// =============================================================================
// Stream Interface
// =============================================================================

template<typename Request, typename Response>
class PluginStream {
public:
    virtual ~PluginStream() = default;
    
    // For server/bidi streaming - send response to client
    virtual bool Send(const Response& response) = 0;
    
    // For client/bidi streaming - receive request from client
    virtual bool Recv(Request* request) = 0;
    
    // Check if stream context is cancelled
    virtual bool IsCancelled() const = 0;
};

// =============================================================================
// Plugin Interface
// =============================================================================


class GoGreeterServicePlugin {
public:
    virtual ~GoGreeterServicePlugin() = default;
    virtual ::example::v1::HelloResponse Bar(const ::example::v1::HelloRequest& request) = 0;
    virtual void BarServerStream(const ::example::v1::HelloRequest& request, 
                                PluginStream<::example::v1::HelloRequest, ::example::v1::HelloResponse>* stream) = 0;
    virtual ::example::v1::HelloResponse BarClientStream(PluginStream<::example::v1::HelloRequest, ::example::v1::HelloResponse>* stream) = 0;
    virtual void BarBidiStream(PluginStream<::example::v1::HelloRequest, ::example::v1::HelloResponse>* stream) = 0;
    virtual ::example::v1::FileStatus UploadFile(PluginStream<::example::v1::FileChunk, ::example::v1::FileStatus>* stream) = 0;
    virtual void DownloadFile(const ::example::v1::DownloadFileRequest& request, 
                                PluginStream<::example::v1::DownloadFileRequest, ::example::v1::FileChunk>* stream) = 0;
    virtual void BidiFile(PluginStream<::example::v1::FileChunk, ::example::v1::FileChunk>* stream) = 0;
    virtual ::example::v1::HelloResponse Trigger(const ::example::v1::TriggerRequest& request) = 0;
    virtual ::example::v1::GoroutinesResponse GetGoroutines(const ::example::v1::GoroutinesRequest& request) = 0;
};

void RegisterGoGreeterServicePlugin(GoGreeterServicePlugin* plugin);
GoGreeterServicePlugin* GetGoGreeterServicePlugin();



} // namespace example::v1


#endif // EXAMPLE_FFI_H_

