// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.
// C++ Plugin Server Header for Synurang FFI

#ifndef EXAMPLE_FFI_H_
#define EXAMPLE_FFI_H_

#include <cstdint>
#include <cstdlib>
#include <functional>
#include <memory>
#include <mutex>
#include <condition_variable>
#include <queue>
#include <thread>
#include <unordered_map>
#include <string>
#include <vector>

#include "example.pb.h"


namespace example::v1 {


// =============================================================================
// Stream Interface
// =============================================================================

template<typename Request, typename Response>
class PluginStream {
public:
    virtual ~PluginStream() = default;
    
    // For server/bidi streaming - send response to client
    virtual bool Send(const Response& response) = 0;
    
    // For client/bidi streaming - receive request from client
    virtual bool Recv(Request* request) = 0;
    
    // Check if stream context is cancelled
    virtual bool IsCancelled() const = 0;
};

// =============================================================================
// Plugin Interface
// =============================================================================


class GoGreeterServicePlugin {
public:
    virtual ~GoGreeterServicePlugin() = default;
    virtual HelloResponse Bar(const HelloRequest& request) = 0;
    virtual void BarServerStream(const HelloRequest& request, 
                                PluginStream<HelloRequest, HelloResponse>* stream) = 0;
    virtual HelloResponse BarClientStream(PluginStream<HelloRequest, HelloResponse>* stream) = 0;
    virtual void BarBidiStream(PluginStream<HelloRequest, HelloResponse>* stream) = 0;
    virtual FileStatus UploadFile(PluginStream<FileChunk, FileStatus>* stream) = 0;
    virtual void DownloadFile(const DownloadFileRequest& request, 
                                PluginStream<DownloadFileRequest, FileChunk>* stream) = 0;
    virtual void BidiFile(PluginStream<FileChunk, FileChunk>* stream) = 0;
    virtual HelloResponse Trigger(const TriggerRequest& request) = 0;
    virtual GoroutinesResponse GetGoroutines(const GoroutinesRequest& request) = 0;
};

void RegisterGoGreeterServicePlugin(GoGreeterServicePlugin* plugin);
GoGreeterServicePlugin* GetGoGreeterServicePlugin();



} // namespace example::v1


#endif // EXAMPLE_FFI_H_

