// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.
// C++ Plugin Server Implementation for Synurang FFI

#include "example_ffi_plugin.h"
#include "example.pb.h"

#include <atomic>
#include <cstring>
#include <iostream>


namespace example::v1 {


// =============================================================================
// Plugin Registration
// =============================================================================

static GoGreeterServicePlugin* g_plugin_GoGreeterService = nullptr;

void RegisterGoGreeterServicePlugin(GoGreeterServicePlugin* plugin) {
    g_plugin_GoGreeterService = plugin;
}

GoGreeterServicePlugin* GetGoGreeterServicePlugin() {
    return g_plugin_GoGreeterService;
}



// =============================================================================
// Stream Handle Management
// =============================================================================

struct StreamResult {
    int status = 0;
    std::string payload;
};

struct StreamContext {
    std::mutex mutex;
    std::condition_variable send_cv;
    std::condition_variable recv_cv;
    std::queue<std::string> send_queue;  // host -> plugin
    std::queue<StreamResult> recv_queue;  // plugin -> host
    std::atomic<bool> closed{false};
    std::atomic<bool> send_closed{false};
    std::thread handler_thread;
};

static std::mutex g_stream_mutex;
static std::unordered_map<uint64_t, std::unique_ptr<StreamContext>> g_streams;
static std::atomic<uint64_t> g_next_handle{1};

static StreamContext* get_stream(uint64_t handle) {
    std::lock_guard<std::mutex> lock(g_stream_mutex);
    auto it = g_streams.find(handle);
    return it != g_streams.end() ? it->second.get() : nullptr;
}

static void append_varint(std::string* out, uint64_t value) {
    while (value >= 0x80) {
        out->push_back(static_cast<char>((value & 0x7f) | 0x80));
        value >>= 7;
    }
    out->push_back(static_cast<char>(value));
}

static std::string encode_ffi_error_payload(const std::string& message, int32_t code = 0, int32_t grpc_code = 2) {
    std::string payload;
    if (code != 0) {
        append_varint(&payload, 8);
        append_varint(&payload, static_cast<uint32_t>(code));
    }
    append_varint(&payload, 18);
    append_varint(&payload, static_cast<uint64_t>(message.size()));
    payload.append(message);
    if (grpc_code != 0) {
        append_varint(&payload, 24);
        append_varint(&payload, static_cast<uint32_t>(grpc_code));
    }
    return payload;
}

static std::string encode_ffi_error_payload(const FfiError& error) {
    return encode_ffi_error_payload(error.what(), error.code(), error.grpc_code());
}

static char* alloc_payload(const std::string& payload) {
    if (payload.empty()) {
        return nullptr;
    }
    char* result = static_cast<char*>(malloc(payload.size()));
    memcpy(result, payload.data(), payload.size());
    return result;
}

static char* make_unary_response(const std::string& payload, int* resp_len, bool is_error) {
    *resp_len = is_error ? -static_cast<int>(payload.size()) : static_cast<int>(payload.size());
    return alloc_payload(payload);
}

static char* make_success_response(const std::string& payload, int* resp_len) {
    return make_unary_response(payload, resp_len, false);
}

static char* make_error_response(const std::string& message, int* resp_len) {
    return make_unary_response(encode_ffi_error_payload(message), resp_len, true);
}

static char* make_error_response(const FfiError& error, int* resp_len) {
    return make_unary_response(encode_ffi_error_payload(error), resp_len, true);
}

static void push_stream_result(StreamContext* ctx, int status, std::string payload) {
    std::lock_guard<std::mutex> lock(ctx->mutex);
    ctx->recv_queue.push(StreamResult{status, std::move(payload)});
    ctx->recv_cv.notify_one();
}

static void close_stream_context(StreamContext* ctx) {
    {
        std::lock_guard<std::mutex> lock(ctx->mutex);
        ctx->closed = true;
    }
    ctx->send_cv.notify_all();
    ctx->recv_cv.notify_all();
}

static void push_stream_error(StreamContext* ctx, const std::string& message) {
    push_stream_result(ctx, -1, encode_ffi_error_payload(message));
}

static void push_stream_error(StreamContext* ctx, const FfiError& error) {
    push_stream_result(ctx, -1, encode_ffi_error_payload(error));
}

// =============================================================================
// Stream Wrapper Implementation
// =============================================================================

template<typename Request, typename Response>
class StreamWrapper : public PluginStream<Request, Response> {
public:
    explicit StreamWrapper(StreamContext* ctx) : ctx_(ctx) {}
    
    bool Send(const Response& response) override {
        if (ctx_->closed) return false;
        std::string data;
        if (!response.SerializeToString(&data)) return false;
        push_stream_result(ctx_, 0, std::move(data));
        return true;
    }
    
    bool Recv(Request* request) override {
        std::unique_lock<std::mutex> lock(ctx_->mutex);
        ctx_->send_cv.wait(lock, [this] { 
            return !ctx_->send_queue.empty() || ctx_->send_closed || ctx_->closed; 
        });
        
        if (ctx_->closed) return false;
        if (ctx_->send_queue.empty()) return false; // EOF
        
        std::string data = std::move(ctx_->send_queue.front());
        ctx_->send_queue.pop();
        lock.unlock();
        
        return request->ParseFromString(data);
    }
    
    bool IsCancelled() const override {
        return ctx_->closed;
    }

private:
    StreamContext* ctx_;
};



} // namespace example::v1


// =============================================================================
// C ABI Exports
// =============================================================================

extern "C" {

// Free memory allocated by plugin
__attribute__((visibility("default")))
void Synurang_Free(void* ptr) {
    free(ptr);
}


// Invoke unary methods for GoGreeterService
__attribute__((visibility("default")))
char* Synurang_Invoke_GoGreeterService(const char* method, const char* data, int data_len, int* resp_len) {
    auto* plugin = example::v1::GetGoGreeterServicePlugin();
    using namespace example::v1;
    if (!plugin) return make_error_response("plugin not registered", resp_len);
    
    std::string method_str(method);
    std::string input;
    if (data != nullptr && data_len > 0) {
        input.assign(data, data_len);
    }
    std::string output;
    bool success = false;
    try {
    if (method_str == "/example.v1.GoGreeterService/Bar") {
        ::example::v1::HelloRequest req;
        if (req.ParseFromString(input)) {
            auto resp = plugin->Bar(req);
            success = resp.SerializeToString(&output);
        }
    }
    if (method_str == "/example.v1.GoGreeterService/Trigger") {
        ::example::v1::TriggerRequest req;
        if (req.ParseFromString(input)) {
            auto resp = plugin->Trigger(req);
            success = resp.SerializeToString(&output);
        }
    }
    if (method_str == "/example.v1.GoGreeterService/GetGoroutines") {
        ::example::v1::GoroutinesRequest req;
        if (req.ParseFromString(input)) {
            auto resp = plugin->GetGoroutines(req);
            success = resp.SerializeToString(&output);
        }
    }
    } catch (const FfiError& e) {
        return make_error_response(e, resp_len);
    } catch (const std::exception& e) {
        return make_error_response(e.what(), resp_len);
    }

    if (success) return make_success_response(output, resp_len);
    return make_error_response("invoke failed for method: " + method_str, resp_len);
}


// Open streaming RPC for GoGreeterService
__attribute__((visibility("default")))
uint64_t Synurang_Stream_GoGreeterService_Open(const char* method) {
    auto* plugin = example::v1::GetGoGreeterServicePlugin();
    if (!plugin) return 0;

    std::string method_str(method);
    using namespace example::v1;
    
    auto ctx = std::make_unique<StreamContext>();
    uint64_t handle = g_next_handle++;
    StreamContext* ctx_ptr = ctx.get();
    
    // Start handler thread
    ctx->handler_thread = std::thread([plugin, method_str, ctx_ptr]() {
        try {
        if (method_str == "/example.v1.GoGreeterService/BarServerStream") {
            // Wait for initial request
            std::unique_lock<std::mutex> lock(ctx_ptr->mutex);
            ctx_ptr->send_cv.wait(lock, [ctx_ptr] { 
                return !ctx_ptr->send_queue.empty() || ctx_ptr->closed; 
            });
            if (ctx_ptr->closed) return;
            
            std::string data = std::move(ctx_ptr->send_queue.front());
            ctx_ptr->send_queue.pop();
            lock.unlock();
            
            ::example::v1::HelloRequest req;
            if (req.ParseFromString(data)) {
                StreamWrapper<::example::v1::HelloRequest, ::example::v1::HelloResponse> wrapper(ctx_ptr);
                plugin->BarServerStream(req, &wrapper);
            } else {
                push_stream_error(ctx_ptr, "failed to parse stream request");
            }
            close_stream_context(ctx_ptr);
            return;
        }
        if (method_str == "/example.v1.GoGreeterService/BarClientStream") {
            StreamWrapper<::example::v1::HelloRequest, ::example::v1::HelloResponse> wrapper(ctx_ptr);
            auto resp = plugin->BarClientStream(&wrapper);
            wrapper.Send(resp);
            close_stream_context(ctx_ptr);
            return;
        }
        if (method_str == "/example.v1.GoGreeterService/BarBidiStream") {
            StreamWrapper<::example::v1::HelloRequest, ::example::v1::HelloResponse> wrapper(ctx_ptr);
            plugin->BarBidiStream(&wrapper);
            close_stream_context(ctx_ptr);
            return;
        }
        if (method_str == "/example.v1.GoGreeterService/UploadFile") {
            StreamWrapper<::example::v1::FileChunk, ::example::v1::FileStatus> wrapper(ctx_ptr);
            auto resp = plugin->UploadFile(&wrapper);
            wrapper.Send(resp);
            close_stream_context(ctx_ptr);
            return;
        }
        if (method_str == "/example.v1.GoGreeterService/DownloadFile") {
            // Wait for initial request
            std::unique_lock<std::mutex> lock(ctx_ptr->mutex);
            ctx_ptr->send_cv.wait(lock, [ctx_ptr] { 
                return !ctx_ptr->send_queue.empty() || ctx_ptr->closed; 
            });
            if (ctx_ptr->closed) return;
            
            std::string data = std::move(ctx_ptr->send_queue.front());
            ctx_ptr->send_queue.pop();
            lock.unlock();
            
            ::example::v1::DownloadFileRequest req;
            if (req.ParseFromString(data)) {
                StreamWrapper<::example::v1::DownloadFileRequest, ::example::v1::FileChunk> wrapper(ctx_ptr);
                plugin->DownloadFile(req, &wrapper);
            } else {
                push_stream_error(ctx_ptr, "failed to parse stream request");
            }
            close_stream_context(ctx_ptr);
            return;
        }
        if (method_str == "/example.v1.GoGreeterService/BidiFile") {
            StreamWrapper<::example::v1::FileChunk, ::example::v1::FileChunk> wrapper(ctx_ptr);
            plugin->BidiFile(&wrapper);
            close_stream_context(ctx_ptr);
            return;
        }
            push_stream_error(ctx_ptr, "unknown method: " + method_str);
            close_stream_context(ctx_ptr);
        } catch (const FfiError& e) {
            push_stream_error(ctx_ptr, e);
            close_stream_context(ctx_ptr);
        } catch (const std::exception& e) {
            push_stream_error(ctx_ptr, e.what());
            close_stream_context(ctx_ptr);
        }
    });

    {
        std::lock_guard<std::mutex> lock(g_stream_mutex);
        g_streams[handle] = std::move(ctx);
    }
    
    return handle;
}




// Global streaming functions

__attribute__((visibility("default")))
int Synurang_Stream_Send(uint64_t handle, const char* data, int data_len) {
    using namespace example::v1;
    auto* ctx = get_stream(handle);
    if (!ctx || ctx->closed) return -1;
    
    std::lock_guard<std::mutex> lock(ctx->mutex);
    ctx->send_queue.emplace(data, data_len);
    ctx->send_cv.notify_one();
    return 0;
}

__attribute__((visibility("default")))
char* Synurang_Stream_Recv(uint64_t handle, int* resp_len, int* status) {
    using namespace example::v1;
    auto* ctx = get_stream(handle);
    if (!ctx) {
        std::string error = encode_ffi_error_payload("stream not found");
        *status = -1;
        *resp_len = static_cast<int>(error.size());
        return alloc_payload(error);
    }
    
    std::unique_lock<std::mutex> lock(ctx->mutex);
    ctx->recv_cv.wait(lock, [ctx] { 
        return !ctx->recv_queue.empty() || ctx->closed; 
    });
    
    if (ctx->recv_queue.empty()) {
        *status = 1; // EOF
        *resp_len = 0;
        return nullptr;
    }
    
    StreamResult result = std::move(ctx->recv_queue.front());
    ctx->recv_queue.pop();

    *resp_len = static_cast<int>(result.payload.size());
    *status = result.status;
    return alloc_payload(result.payload);
}

__attribute__((visibility("default")))
void Synurang_Stream_CloseSend(uint64_t handle) {
    using namespace example::v1;
    auto* ctx = get_stream(handle);
    if (!ctx) return;

    {
        std::lock_guard<std::mutex> lock(ctx->mutex);
        ctx->send_closed = true;
    }
    ctx->send_cv.notify_all();
}

__attribute__((visibility("default")))
void Synurang_Stream_Close(uint64_t handle) {
    using namespace example::v1;
    std::unique_ptr<StreamContext> ctx;
    {
        std::lock_guard<std::mutex> lock(g_stream_mutex);
        auto it = g_streams.find(handle);
        if (it == g_streams.end()) return;
        ctx = std::move(it->second);
        g_streams.erase(it);
    }

    {
        std::lock_guard<std::mutex> lock(ctx->mutex);
        ctx->closed = true;
    }
    ctx->send_cv.notify_all();
    ctx->recv_cv.notify_all();

    if (ctx->handler_thread.joinable()) {
        ctx->handler_thread.join();
    }
}


} // extern "C"

