// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.
// C++ Plugin Server Implementation for Synurang FFI

#include "example_ffi_plugin.h"
#include "example.pb.h"

#include <atomic>
#include <cstring>
#include <iostream>


namespace example::v1 {


// =============================================================================
// Plugin Registration
// =============================================================================

static GoGreeterServicePlugin* g_plugin_GoGreeterService = nullptr;

void RegisterGoGreeterServicePlugin(GoGreeterServicePlugin* plugin) {
    g_plugin_GoGreeterService = plugin;
}

GoGreeterServicePlugin* GetGoGreeterServicePlugin() {
    return g_plugin_GoGreeterService;
}



// =============================================================================
// Stream Handle Management
// =============================================================================

struct StreamContext {
    std::mutex mutex;
    std::condition_variable send_cv;
    std::condition_variable recv_cv;
    std::queue<std::string> send_queue;  // host -> plugin
    std::queue<std::string> recv_queue;  // plugin -> host
    std::atomic<bool> closed{false};
    std::atomic<bool> send_closed{false};
    std::thread handler_thread;
};

static std::mutex g_stream_mutex;
static std::unordered_map<uint64_t, std::unique_ptr<StreamContext>> g_streams;
static std::atomic<uint64_t> g_next_handle{1};

static StreamContext* get_stream(uint64_t handle) {
    std::lock_guard<std::mutex> lock(g_stream_mutex);
    auto it = g_streams.find(handle);
    return it != g_streams.end() ? it->second.get() : nullptr;
}

// =============================================================================
// Stream Wrapper Implementation
// =============================================================================

template<typename Request, typename Response>
class StreamWrapper : public PluginStream<Request, Response> {
public:
    explicit StreamWrapper(StreamContext* ctx) : ctx_(ctx) {}
    
    bool Send(const Response& response) override {
        if (ctx_->closed) return false;
        std::string data;
        if (!response.SerializeToString(&data)) return false;
        
        std::lock_guard<std::mutex> lock(ctx_->mutex);
        // Format: [status:1][payload]
        std::string result(1 + data.size(), '\0');
        result[0] = 0; // success
        std::memcpy(&result[1], data.data(), data.size());
        ctx_->recv_queue.push(std::move(result));
        ctx_->recv_cv.notify_one();
        return true;
    }
    
    bool Recv(Request* request) override {
        std::unique_lock<std::mutex> lock(ctx_->mutex);
        ctx_->send_cv.wait(lock, [this] { 
            return !ctx_->send_queue.empty() || ctx_->send_closed || ctx_->closed; 
        });
        
        if (ctx_->closed) return false;
        if (ctx_->send_queue.empty()) return false; // EOF
        
        std::string data = std::move(ctx_->send_queue.front());
        ctx_->send_queue.pop();
        lock.unlock();
        
        return request->ParseFromString(data);
    }
    
    bool IsCancelled() const override {
        return ctx_->closed;
    }

private:
    StreamContext* ctx_;
};



} // namespace example::v1


// =============================================================================
// C ABI Exports
// =============================================================================

extern "C" {

// Free memory allocated by plugin
__attribute__((visibility("default")))
void Synurang_Free(void* ptr) {
    free(ptr);
}


// Invoke unary methods for GoGreeterService
__attribute__((visibility("default")))
char* Synurang_Invoke_GoGreeterService(const char* method, const char* data, int data_len, int* resp_len) {
    auto* plugin = example::v1::GetGoGreeterServicePlugin();
    if (!plugin) {
        const char* err = "plugin not registered";
        char* result = static_cast<char*>(malloc(1 + strlen(err)));
        result[0] = 1; // error
        memcpy(result + 1, err, strlen(err));
        *resp_len = 1 + strlen(err);
        return result;
    }
    
    std::string method_str(method);
    std::string input(data, data_len);
    std::string output;
    bool success = false;
    if (method_str == "/example.v1.GoGreeterService/Bar") {
        ::example::v1::HelloRequest req;
        if (req.ParseFromString(input)) {
            auto resp = plugin->Bar(req);
            success = resp.SerializeToString(&output);
        }
    }
    if (method_str == "/example.v1.GoGreeterService/Trigger") {
        ::example::v1::TriggerRequest req;
        if (req.ParseFromString(input)) {
            auto resp = plugin->Trigger(req);
            success = resp.SerializeToString(&output);
        }
    }
    if (method_str == "/example.v1.GoGreeterService/GetGoroutines") {
        ::example::v1::GoroutinesRequest req;
        if (req.ParseFromString(input)) {
            auto resp = plugin->GetGoroutines(req);
            success = resp.SerializeToString(&output);
        }
    }

    if (success) {
        char* result = static_cast<char*>(malloc(1 + output.size()));
        result[0] = 0; // success
        memcpy(result + 1, output.data(), output.size());
        *resp_len = 1 + output.size();
        return result;
    } else {
        std::string err = "invoke failed for method: " + method_str;
        char* result = static_cast<char*>(malloc(1 + err.size()));
        result[0] = 1; // error
        memcpy(result + 1, err.data(), err.size());
        *resp_len = 1 + err.size();
        return result;
    }
}


// Open streaming RPC for GoGreeterService
__attribute__((visibility("default")))
uint64_t Synurang_Stream_GoGreeterService_Open(const char* method) {
    auto* plugin = example::v1::GetGoGreeterServicePlugin();
    if (!plugin) return 0;

    std::string method_str(method);
    using namespace example::v1;
    
    auto ctx = std::make_unique<StreamContext>();
    uint64_t handle = g_next_handle++;
    StreamContext* ctx_ptr = ctx.get();
    
    // Start handler thread
    ctx->handler_thread = std::thread([plugin, method_str, ctx_ptr]() {
        if (method_str == "/example.v1.GoGreeterService/BarServerStream") {
            // Wait for initial request
            std::unique_lock<std::mutex> lock(ctx_ptr->mutex);
            ctx_ptr->send_cv.wait(lock, [ctx_ptr] { 
                return !ctx_ptr->send_queue.empty() || ctx_ptr->closed; 
            });
            if (ctx_ptr->closed) return;
            
            std::string data = std::move(ctx_ptr->send_queue.front());
            ctx_ptr->send_queue.pop();
            lock.unlock();
            
            ::example::v1::HelloRequest req;
            if (req.ParseFromString(data)) {
                StreamWrapper<::example::v1::HelloRequest, ::example::v1::HelloResponse> wrapper(ctx_ptr);
                plugin->BarServerStream(req, &wrapper);
            }
            // Signal EOF after streaming completes
            {
                std::lock_guard<std::mutex> lock(ctx_ptr->mutex);
                ctx_ptr->closed = true;
            }
            ctx_ptr->recv_cv.notify_all();
            return;
        }
        if (method_str == "/example.v1.GoGreeterService/BarClientStream") {
            StreamWrapper<::example::v1::HelloRequest, ::example::v1::HelloResponse> wrapper(ctx_ptr);
            auto resp = plugin->BarClientStream(&wrapper);
            wrapper.Send(resp);
            // Signal EOF after response sent
            {
                std::lock_guard<std::mutex> lock(ctx_ptr->mutex);
                ctx_ptr->closed = true;
            }
            ctx_ptr->recv_cv.notify_all();
            return;
        }
        if (method_str == "/example.v1.GoGreeterService/BarBidiStream") {
            StreamWrapper<::example::v1::HelloRequest, ::example::v1::HelloResponse> wrapper(ctx_ptr);
            plugin->BarBidiStream(&wrapper);
            // Signal EOF after bidi streaming completes
            {
                std::lock_guard<std::mutex> lock(ctx_ptr->mutex);
                ctx_ptr->closed = true;
            }
            ctx_ptr->recv_cv.notify_all();
            return;
        }
        if (method_str == "/example.v1.GoGreeterService/UploadFile") {
            StreamWrapper<::example::v1::FileChunk, ::example::v1::FileStatus> wrapper(ctx_ptr);
            auto resp = plugin->UploadFile(&wrapper);
            wrapper.Send(resp);
            // Signal EOF after response sent
            {
                std::lock_guard<std::mutex> lock(ctx_ptr->mutex);
                ctx_ptr->closed = true;
            }
            ctx_ptr->recv_cv.notify_all();
            return;
        }
        if (method_str == "/example.v1.GoGreeterService/DownloadFile") {
            // Wait for initial request
            std::unique_lock<std::mutex> lock(ctx_ptr->mutex);
            ctx_ptr->send_cv.wait(lock, [ctx_ptr] { 
                return !ctx_ptr->send_queue.empty() || ctx_ptr->closed; 
            });
            if (ctx_ptr->closed) return;
            
            std::string data = std::move(ctx_ptr->send_queue.front());
            ctx_ptr->send_queue.pop();
            lock.unlock();
            
            ::example::v1::DownloadFileRequest req;
            if (req.ParseFromString(data)) {
                StreamWrapper<::example::v1::DownloadFileRequest, ::example::v1::FileChunk> wrapper(ctx_ptr);
                plugin->DownloadFile(req, &wrapper);
            }
            // Signal EOF after streaming completes
            {
                std::lock_guard<std::mutex> lock(ctx_ptr->mutex);
                ctx_ptr->closed = true;
            }
            ctx_ptr->recv_cv.notify_all();
            return;
        }
        if (method_str == "/example.v1.GoGreeterService/BidiFile") {
            StreamWrapper<::example::v1::FileChunk, ::example::v1::FileChunk> wrapper(ctx_ptr);
            plugin->BidiFile(&wrapper);
            // Signal EOF after bidi streaming completes
            {
                std::lock_guard<std::mutex> lock(ctx_ptr->mutex);
                ctx_ptr->closed = true;
            }
            ctx_ptr->recv_cv.notify_all();
            return;
        }
    });

    {
        std::lock_guard<std::mutex> lock(g_stream_mutex);
        g_streams[handle] = std::move(ctx);
    }
    
    return handle;
}




// Global streaming functions

__attribute__((visibility("default")))
int Synurang_Stream_Send(uint64_t handle, const char* data, int data_len) {
    using namespace example::v1;
    auto* ctx = get_stream(handle);
    if (!ctx || ctx->closed) return -1;
    
    std::lock_guard<std::mutex> lock(ctx->mutex);
    ctx->send_queue.emplace(data, data_len);
    ctx->send_cv.notify_one();
    return 0;
}

__attribute__((visibility("default")))
char* Synurang_Stream_Recv(uint64_t handle, int* resp_len, int* status) {
    using namespace example::v1;
    auto* ctx = get_stream(handle);
    if (!ctx) {
        *status = 2; // error
        *resp_len = 0;
        return nullptr;
    }
    
    std::unique_lock<std::mutex> lock(ctx->mutex);
    ctx->recv_cv.wait(lock, [ctx] { 
        return !ctx->recv_queue.empty() || ctx->closed; 
    });
    
    if (ctx->recv_queue.empty()) {
        *status = 1; // EOF
        *resp_len = 0;
        return nullptr;
    }
    
    std::string data = std::move(ctx->recv_queue.front());
    ctx->recv_queue.pop();
    
    char* result = static_cast<char*>(malloc(data.size()));
    memcpy(result, data.data(), data.size());
    *resp_len = data.size();
    *status = 0; // data
    return result;
}

__attribute__((visibility("default")))
void Synurang_Stream_CloseSend(uint64_t handle) {
    using namespace example::v1;
    auto* ctx = get_stream(handle);
    if (!ctx) return;

    {
        std::lock_guard<std::mutex> lock(ctx->mutex);
        ctx->send_closed = true;
    }
    ctx->send_cv.notify_all();
}

__attribute__((visibility("default")))
void Synurang_Stream_Close(uint64_t handle) {
    using namespace example::v1;
    std::unique_ptr<StreamContext> ctx;
    {
        std::lock_guard<std::mutex> lock(g_stream_mutex);
        auto it = g_streams.find(handle);
        if (it == g_streams.end()) return;
        ctx = std::move(it->second);
        g_streams.erase(it);
    }

    {
        std::lock_guard<std::mutex> lock(ctx->mutex);
        ctx->closed = true;
    }
    ctx->send_cv.notify_all();
    ctx->recv_cv.notify_all();

    if (ctx->handler_thread.joinable()) {
        ctx->handler_thread.join();
    }
}


} // extern "C"

