// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.

#ifndef CORE_FFI_H_
#define CORE_FFI_H_

#include <string>
#include <functional>
#include <memory>

#include "core.pb.h"
#include "google/protobuf/empty.pb.h"

namespace core::v1 {


// =============================================================================
// HealthService FFI Server Interface
// =============================================================================

class HealthServiceFfiServer {
public:
  virtual ~HealthServiceFfiServer() = default;
  virtual ::core::v1::PingResponse Ping(const ::google::protobuf::Empty& request) = 0;
};

// =============================================================================
// HealthService FFI Dispatcher
// =============================================================================

inline std::string HealthServiceInvoke(HealthServiceFfiServer* server, const std::string& method, const std::string& data) {
  if (method == "/core.v1.HealthService/Ping") {
    ::google::protobuf::Empty req;
    if (!req.ParseFromString(data)) {
      return "";  // Parse error
    }
    ::core::v1::PingResponse resp = server->Ping(req);
    return resp.SerializeAsString();
  }
  return "";  // Unknown method
}

// =============================================================================
// HealthService FFI Client Connection - routes calls through FFI
// =============================================================================

class HealthServiceFfiChannel {
public:
  explicit HealthServiceFfiChannel(HealthServiceFfiServer* server) : server_(server) {}

  template<typename Request, typename Response>
  bool Invoke(const std::string& method, const Request& request, Response* response) {
    std::string data = request.SerializeAsString();
    std::string result = ::core::v1::HealthServiceInvoke(server_, method, data);
    if (result.empty()) {
      return false;
    }
    return response->ParseFromString(result);
  }

private:
  HealthServiceFfiServer* server_;
};

// =============================================================================
// HealthService FFI Client
// =============================================================================

class HealthServiceFfiClient {
public:
  explicit HealthServiceFfiClient(HealthServiceFfiChannel* conn) : conn_(conn) {}
  explicit HealthServiceFfiClient(HealthServiceFfiServer* server)
      : owned_conn_(std::make_unique<HealthServiceFfiChannel>(server)), conn_(owned_conn_.get()) {}

  bool Ping(const ::google::protobuf::Empty& request, ::core::v1::PingResponse* response) {
    return conn_->Invoke("/core.v1.HealthService/Ping", request, response);
  }

private:
  std::unique_ptr<HealthServiceFfiChannel> owned_conn_;
  HealthServiceFfiChannel* conn_;
};



} // namespace core::v1

#endif // CORE_FFI_H_

