// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: example.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoGreeterService_Bar_FullMethodName             = "/example.v1.GoGreeterService/Bar"
	GoGreeterService_BarServerStream_FullMethodName = "/example.v1.GoGreeterService/BarServerStream"
	GoGreeterService_BarClientStream_FullMethodName = "/example.v1.GoGreeterService/BarClientStream"
	GoGreeterService_BarBidiStream_FullMethodName   = "/example.v1.GoGreeterService/BarBidiStream"
	GoGreeterService_UploadFile_FullMethodName      = "/example.v1.GoGreeterService/UploadFile"
	GoGreeterService_DownloadFile_FullMethodName    = "/example.v1.GoGreeterService/DownloadFile"
	GoGreeterService_BidiFile_FullMethodName        = "/example.v1.GoGreeterService/BidiFile"
	GoGreeterService_Trigger_FullMethodName         = "/example.v1.GoGreeterService/Trigger"
	GoGreeterService_GetGoroutines_FullMethodName   = "/example.v1.GoGreeterService/GetGoroutines"
)

// GoGreeterServiceClient is the client API for GoGreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// GoGreeterService - Go-side server, Dart client calls this
// =============================================================================
type GoGreeterServiceClient interface {
	// Simple RPC - single request, single response
	Bar(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// Server-side streaming RPC - single request, stream of responses
	BarServerStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelloResponse], error)
	// Client-side streaming RPC - stream of requests, single response
	BarClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloRequest, HelloResponse], error)
	// Bidirectional streaming RPC - stream of requests, stream of responses
	BarBidiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HelloRequest, HelloResponse], error)
	// File Streaming RPCs
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, FileStatus], error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	BidiFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileChunk, FileChunk], error)
	// Trigger - Generic entry point to trigger Go -> Dart calls (Demo specific)
	Trigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	GetGoroutines(ctx context.Context, in *GoroutinesRequest, opts ...grpc.CallOption) (*GoroutinesResponse, error)
}

type goGreeterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoGreeterServiceClient(cc grpc.ClientConnInterface) GoGreeterServiceClient {
	return &goGreeterServiceClient{cc}
}

func (c *goGreeterServiceClient) Bar(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, GoGreeterService_Bar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goGreeterServiceClient) BarServerStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelloResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoGreeterService_ServiceDesc.Streams[0], GoGreeterService_BarServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloRequest, HelloResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_BarServerStreamClient = grpc.ServerStreamingClient[HelloResponse]

func (c *goGreeterServiceClient) BarClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloRequest, HelloResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoGreeterService_ServiceDesc.Streams[1], GoGreeterService_BarClientStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloRequest, HelloResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_BarClientStreamClient = grpc.ClientStreamingClient[HelloRequest, HelloResponse]

func (c *goGreeterServiceClient) BarBidiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HelloRequest, HelloResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoGreeterService_ServiceDesc.Streams[2], GoGreeterService_BarBidiStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloRequest, HelloResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_BarBidiStreamClient = grpc.BidiStreamingClient[HelloRequest, HelloResponse]

func (c *goGreeterServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, FileStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoGreeterService_ServiceDesc.Streams[3], GoGreeterService_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, FileStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_UploadFileClient = grpc.ClientStreamingClient[FileChunk, FileStatus]

func (c *goGreeterServiceClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoGreeterService_ServiceDesc.Streams[4], GoGreeterService_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadFileRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_DownloadFileClient = grpc.ServerStreamingClient[FileChunk]

func (c *goGreeterServiceClient) BidiFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileChunk, FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoGreeterService_ServiceDesc.Streams[5], GoGreeterService_BidiFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, FileChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_BidiFileClient = grpc.BidiStreamingClient[FileChunk, FileChunk]

func (c *goGreeterServiceClient) Trigger(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, GoGreeterService_Trigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goGreeterServiceClient) GetGoroutines(ctx context.Context, in *GoroutinesRequest, opts ...grpc.CallOption) (*GoroutinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoroutinesResponse)
	err := c.cc.Invoke(ctx, GoGreeterService_GetGoroutines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoGreeterServiceServer is the server API for GoGreeterService service.
// All implementations must embed UnimplementedGoGreeterServiceServer
// for forward compatibility.
//
// =============================================================================
// GoGreeterService - Go-side server, Dart client calls this
// =============================================================================
type GoGreeterServiceServer interface {
	// Simple RPC - single request, single response
	Bar(context.Context, *HelloRequest) (*HelloResponse, error)
	// Server-side streaming RPC - single request, stream of responses
	BarServerStream(*HelloRequest, grpc.ServerStreamingServer[HelloResponse]) error
	// Client-side streaming RPC - stream of requests, single response
	BarClientStream(grpc.ClientStreamingServer[HelloRequest, HelloResponse]) error
	// Bidirectional streaming RPC - stream of requests, stream of responses
	BarBidiStream(grpc.BidiStreamingServer[HelloRequest, HelloResponse]) error
	// File Streaming RPCs
	UploadFile(grpc.ClientStreamingServer[FileChunk, FileStatus]) error
	DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[FileChunk]) error
	BidiFile(grpc.BidiStreamingServer[FileChunk, FileChunk]) error
	// Trigger - Generic entry point to trigger Go -> Dart calls (Demo specific)
	Trigger(context.Context, *TriggerRequest) (*HelloResponse, error)
	GetGoroutines(context.Context, *GoroutinesRequest) (*GoroutinesResponse, error)
	mustEmbedUnimplementedGoGreeterServiceServer()
}

// UnimplementedGoGreeterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoGreeterServiceServer struct{}

func (UnimplementedGoGreeterServiceServer) Bar(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bar not implemented")
}
func (UnimplementedGoGreeterServiceServer) BarServerStream(*HelloRequest, grpc.ServerStreamingServer[HelloResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BarServerStream not implemented")
}
func (UnimplementedGoGreeterServiceServer) BarClientStream(grpc.ClientStreamingServer[HelloRequest, HelloResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BarClientStream not implemented")
}
func (UnimplementedGoGreeterServiceServer) BarBidiStream(grpc.BidiStreamingServer[HelloRequest, HelloResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BarBidiStream not implemented")
}
func (UnimplementedGoGreeterServiceServer) UploadFile(grpc.ClientStreamingServer[FileChunk, FileStatus]) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedGoGreeterServiceServer) DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedGoGreeterServiceServer) BidiFile(grpc.BidiStreamingServer[FileChunk, FileChunk]) error {
	return status.Errorf(codes.Unimplemented, "method BidiFile not implemented")
}
func (UnimplementedGoGreeterServiceServer) Trigger(context.Context, *TriggerRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trigger not implemented")
}
func (UnimplementedGoGreeterServiceServer) GetGoroutines(context.Context, *GoroutinesRequest) (*GoroutinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoroutines not implemented")
}
func (UnimplementedGoGreeterServiceServer) mustEmbedUnimplementedGoGreeterServiceServer() {}
func (UnimplementedGoGreeterServiceServer) testEmbeddedByValue()                          {}

// UnsafeGoGreeterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoGreeterServiceServer will
// result in compilation errors.
type UnsafeGoGreeterServiceServer interface {
	mustEmbedUnimplementedGoGreeterServiceServer()
}

func RegisterGoGreeterServiceServer(s grpc.ServiceRegistrar, srv GoGreeterServiceServer) {
	// If the following call pancis, it indicates UnimplementedGoGreeterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoGreeterService_ServiceDesc, srv)
}

func _GoGreeterService_Bar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoGreeterServiceServer).Bar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoGreeterService_Bar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoGreeterServiceServer).Bar(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoGreeterService_BarServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoGreeterServiceServer).BarServerStream(m, &grpc.GenericServerStream[HelloRequest, HelloResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_BarServerStreamServer = grpc.ServerStreamingServer[HelloResponse]

func _GoGreeterService_BarClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GoGreeterServiceServer).BarClientStream(&grpc.GenericServerStream[HelloRequest, HelloResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_BarClientStreamServer = grpc.ClientStreamingServer[HelloRequest, HelloResponse]

func _GoGreeterService_BarBidiStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GoGreeterServiceServer).BarBidiStream(&grpc.GenericServerStream[HelloRequest, HelloResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_BarBidiStreamServer = grpc.BidiStreamingServer[HelloRequest, HelloResponse]

func _GoGreeterService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GoGreeterServiceServer).UploadFile(&grpc.GenericServerStream[FileChunk, FileStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_UploadFileServer = grpc.ClientStreamingServer[FileChunk, FileStatus]

func _GoGreeterService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoGreeterServiceServer).DownloadFile(m, &grpc.GenericServerStream[DownloadFileRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_DownloadFileServer = grpc.ServerStreamingServer[FileChunk]

func _GoGreeterService_BidiFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GoGreeterServiceServer).BidiFile(&grpc.GenericServerStream[FileChunk, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoGreeterService_BidiFileServer = grpc.BidiStreamingServer[FileChunk, FileChunk]

func _GoGreeterService_Trigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoGreeterServiceServer).Trigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoGreeterService_Trigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoGreeterServiceServer).Trigger(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoGreeterService_GetGoroutines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoroutinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoGreeterServiceServer).GetGoroutines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoGreeterService_GetGoroutines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoGreeterServiceServer).GetGoroutines(ctx, req.(*GoroutinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoGreeterService_ServiceDesc is the grpc.ServiceDesc for GoGreeterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoGreeterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.v1.GoGreeterService",
	HandlerType: (*GoGreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bar",
			Handler:    _GoGreeterService_Bar_Handler,
		},
		{
			MethodName: "Trigger",
			Handler:    _GoGreeterService_Trigger_Handler,
		},
		{
			MethodName: "GetGoroutines",
			Handler:    _GoGreeterService_GetGoroutines_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BarServerStream",
			Handler:       _GoGreeterService_BarServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BarClientStream",
			Handler:       _GoGreeterService_BarClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BarBidiStream",
			Handler:       _GoGreeterService_BarBidiStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _GoGreeterService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _GoGreeterService_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidiFile",
			Handler:       _GoGreeterService_BidiFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "example.proto",
}

const (
	DartGreeterService_Foo_FullMethodName              = "/example.v1.DartGreeterService/Foo"
	DartGreeterService_FooServerStream_FullMethodName  = "/example.v1.DartGreeterService/FooServerStream"
	DartGreeterService_FooClientStream_FullMethodName  = "/example.v1.DartGreeterService/FooClientStream"
	DartGreeterService_FooBidiStream_FullMethodName    = "/example.v1.DartGreeterService/FooBidiStream"
	DartGreeterService_DartUploadFile_FullMethodName   = "/example.v1.DartGreeterService/DartUploadFile"
	DartGreeterService_DartDownloadFile_FullMethodName = "/example.v1.DartGreeterService/DartDownloadFile"
	DartGreeterService_DartBidiFile_FullMethodName     = "/example.v1.DartGreeterService/DartBidiFile"
)

// DartGreeterServiceClient is the client API for DartGreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// DartGreeterService - Dart-side server, Go client calls this
// =============================================================================
type DartGreeterServiceClient interface {
	// Simple RPC - single request, single response
	Foo(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// Server-side streaming RPC - single request, stream of responses
	FooServerStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelloResponse], error)
	// Client-side streaming RPC - stream of requests, single response
	FooClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloRequest, HelloResponse], error)
	// Bidirectional streaming RPC - stream of requests, stream of responses
	FooBidiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HelloRequest, HelloResponse], error)
	// File Streaming RPCs
	DartUploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, FileStatus], error)
	DartDownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	DartBidiFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileChunk, FileChunk], error)
}

type dartGreeterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDartGreeterServiceClient(cc grpc.ClientConnInterface) DartGreeterServiceClient {
	return &dartGreeterServiceClient{cc}
}

func (c *dartGreeterServiceClient) Foo(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, DartGreeterService_Foo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dartGreeterServiceClient) FooServerStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelloResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DartGreeterService_ServiceDesc.Streams[0], DartGreeterService_FooServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloRequest, HelloResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_FooServerStreamClient = grpc.ServerStreamingClient[HelloResponse]

func (c *dartGreeterServiceClient) FooClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloRequest, HelloResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DartGreeterService_ServiceDesc.Streams[1], DartGreeterService_FooClientStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloRequest, HelloResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_FooClientStreamClient = grpc.ClientStreamingClient[HelloRequest, HelloResponse]

func (c *dartGreeterServiceClient) FooBidiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HelloRequest, HelloResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DartGreeterService_ServiceDesc.Streams[2], DartGreeterService_FooBidiStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloRequest, HelloResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_FooBidiStreamClient = grpc.BidiStreamingClient[HelloRequest, HelloResponse]

func (c *dartGreeterServiceClient) DartUploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, FileStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DartGreeterService_ServiceDesc.Streams[3], DartGreeterService_DartUploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, FileStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_DartUploadFileClient = grpc.ClientStreamingClient[FileChunk, FileStatus]

func (c *dartGreeterServiceClient) DartDownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DartGreeterService_ServiceDesc.Streams[4], DartGreeterService_DartDownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadFileRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_DartDownloadFileClient = grpc.ServerStreamingClient[FileChunk]

func (c *dartGreeterServiceClient) DartBidiFile(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileChunk, FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DartGreeterService_ServiceDesc.Streams[5], DartGreeterService_DartBidiFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, FileChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_DartBidiFileClient = grpc.BidiStreamingClient[FileChunk, FileChunk]

// DartGreeterServiceServer is the server API for DartGreeterService service.
// All implementations must embed UnimplementedDartGreeterServiceServer
// for forward compatibility.
//
// =============================================================================
// DartGreeterService - Dart-side server, Go client calls this
// =============================================================================
type DartGreeterServiceServer interface {
	// Simple RPC - single request, single response
	Foo(context.Context, *HelloRequest) (*HelloResponse, error)
	// Server-side streaming RPC - single request, stream of responses
	FooServerStream(*HelloRequest, grpc.ServerStreamingServer[HelloResponse]) error
	// Client-side streaming RPC - stream of requests, single response
	FooClientStream(grpc.ClientStreamingServer[HelloRequest, HelloResponse]) error
	// Bidirectional streaming RPC - stream of requests, stream of responses
	FooBidiStream(grpc.BidiStreamingServer[HelloRequest, HelloResponse]) error
	// File Streaming RPCs
	DartUploadFile(grpc.ClientStreamingServer[FileChunk, FileStatus]) error
	DartDownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[FileChunk]) error
	DartBidiFile(grpc.BidiStreamingServer[FileChunk, FileChunk]) error
	mustEmbedUnimplementedDartGreeterServiceServer()
}

// UnimplementedDartGreeterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDartGreeterServiceServer struct{}

func (UnimplementedDartGreeterServiceServer) Foo(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Foo not implemented")
}
func (UnimplementedDartGreeterServiceServer) FooServerStream(*HelloRequest, grpc.ServerStreamingServer[HelloResponse]) error {
	return status.Errorf(codes.Unimplemented, "method FooServerStream not implemented")
}
func (UnimplementedDartGreeterServiceServer) FooClientStream(grpc.ClientStreamingServer[HelloRequest, HelloResponse]) error {
	return status.Errorf(codes.Unimplemented, "method FooClientStream not implemented")
}
func (UnimplementedDartGreeterServiceServer) FooBidiStream(grpc.BidiStreamingServer[HelloRequest, HelloResponse]) error {
	return status.Errorf(codes.Unimplemented, "method FooBidiStream not implemented")
}
func (UnimplementedDartGreeterServiceServer) DartUploadFile(grpc.ClientStreamingServer[FileChunk, FileStatus]) error {
	return status.Errorf(codes.Unimplemented, "method DartUploadFile not implemented")
}
func (UnimplementedDartGreeterServiceServer) DartDownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DartDownloadFile not implemented")
}
func (UnimplementedDartGreeterServiceServer) DartBidiFile(grpc.BidiStreamingServer[FileChunk, FileChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DartBidiFile not implemented")
}
func (UnimplementedDartGreeterServiceServer) mustEmbedUnimplementedDartGreeterServiceServer() {}
func (UnimplementedDartGreeterServiceServer) testEmbeddedByValue()                            {}

// UnsafeDartGreeterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DartGreeterServiceServer will
// result in compilation errors.
type UnsafeDartGreeterServiceServer interface {
	mustEmbedUnimplementedDartGreeterServiceServer()
}

func RegisterDartGreeterServiceServer(s grpc.ServiceRegistrar, srv DartGreeterServiceServer) {
	// If the following call pancis, it indicates UnimplementedDartGreeterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DartGreeterService_ServiceDesc, srv)
}

func _DartGreeterService_Foo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DartGreeterServiceServer).Foo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DartGreeterService_Foo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DartGreeterServiceServer).Foo(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DartGreeterService_FooServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DartGreeterServiceServer).FooServerStream(m, &grpc.GenericServerStream[HelloRequest, HelloResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_FooServerStreamServer = grpc.ServerStreamingServer[HelloResponse]

func _DartGreeterService_FooClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DartGreeterServiceServer).FooClientStream(&grpc.GenericServerStream[HelloRequest, HelloResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_FooClientStreamServer = grpc.ClientStreamingServer[HelloRequest, HelloResponse]

func _DartGreeterService_FooBidiStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DartGreeterServiceServer).FooBidiStream(&grpc.GenericServerStream[HelloRequest, HelloResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_FooBidiStreamServer = grpc.BidiStreamingServer[HelloRequest, HelloResponse]

func _DartGreeterService_DartUploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DartGreeterServiceServer).DartUploadFile(&grpc.GenericServerStream[FileChunk, FileStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_DartUploadFileServer = grpc.ClientStreamingServer[FileChunk, FileStatus]

func _DartGreeterService_DartDownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DartGreeterServiceServer).DartDownloadFile(m, &grpc.GenericServerStream[DownloadFileRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_DartDownloadFileServer = grpc.ServerStreamingServer[FileChunk]

func _DartGreeterService_DartBidiFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DartGreeterServiceServer).DartBidiFile(&grpc.GenericServerStream[FileChunk, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DartGreeterService_DartBidiFileServer = grpc.BidiStreamingServer[FileChunk, FileChunk]

// DartGreeterService_ServiceDesc is the grpc.ServiceDesc for DartGreeterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DartGreeterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.v1.DartGreeterService",
	HandlerType: (*DartGreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Foo",
			Handler:    _DartGreeterService_Foo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FooServerStream",
			Handler:       _DartGreeterService_FooServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FooClientStream",
			Handler:       _DartGreeterService_FooClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FooBidiStream",
			Handler:       _DartGreeterService_FooBidiStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DartUploadFile",
			Handler:       _DartGreeterService_DartUploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DartDownloadFile",
			Handler:       _DartGreeterService_DartDownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DartBidiFile",
			Handler:       _DartGreeterService_DartBidiFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "example.proto",
}
