// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.
// Rust Plugin Server Implementation for Synurang FFI

// #![allow(unused_imports)]
// #![allow(dead_code)]

use prost::Message;
use std::collections::HashMap;
use std::ffi::{c_char, c_int, c_void, CStr};
use std::ptr;
use std::sync::{Arc, Mutex, RwLock};
use std::sync::atomic::{AtomicU64, Ordering};

// =============================================================================
// Stream Infrastructure
// =============================================================================

struct StreamContext {
    send_queue: Mutex<Vec<Vec<u8>>>,  // host -> plugin
    recv_queue: Mutex<Vec<Vec<u8>>>,  // plugin -> host
    send_cv: std::sync::Condvar,
    recv_cv: std::sync::Condvar,
    closed: std::sync::atomic::AtomicBool,
    send_closed: std::sync::atomic::AtomicBool,
}

impl StreamContext {
    fn new() -> Self {
        Self {
            send_queue: Mutex::new(Vec::new()),
            recv_queue: Mutex::new(Vec::new()),
            send_cv: std::sync::Condvar::new(),
            recv_cv: std::sync::Condvar::new(),
            closed: std::sync::atomic::AtomicBool::new(false),
            send_closed: std::sync::atomic::AtomicBool::new(false),
        }
    }
    
    fn send_to_plugin(&self, data: Vec<u8>) {
        if let Ok(mut queue) = self.send_queue.lock() {
            queue.push(data);
            self.send_cv.notify_one();
        }
    }
    
    fn recv_from_plugin(&self) -> Option<Vec<u8>> {
        let mut queue = self.recv_queue.lock().ok()?;
        loop {
            if !queue.is_empty() {
                return Some(queue.remove(0));
            }
            if self.closed.load(Ordering::SeqCst) {
                return None;
            }
            queue = self.recv_cv.wait(queue).ok()?;
        }
    }
    
    fn close(&self) {
        // Hold send_queue lock to prevent lost wakeup on send_cv
        {
            let _guard = self.send_queue.lock();
            self.closed.store(true, Ordering::SeqCst);
        }
        self.send_cv.notify_all();
        // Hold recv_queue lock to prevent lost wakeup on recv_cv
        {
            let _guard = self.recv_queue.lock();
        }
        self.recv_cv.notify_all();
    }
    
    fn is_closed(&self) -> bool {
        self.closed.load(Ordering::SeqCst)
    }
}

lazy_static::lazy_static! {
    static ref STREAMS: RwLock<HashMap<u64, Arc<StreamContext>>> = RwLock::new(HashMap::new());
    static ref NEXT_HANDLE: AtomicU64 = AtomicU64::new(1);
}

fn get_stream(handle: u64) -> Option<Arc<StreamContext>> {
    STREAMS.read().ok()?.get(&handle).cloned()
}

// =============================================================================
// Plugin Trait
// =============================================================================


pub trait GoGreeterServicePlugin: Send + Sync + 'static {
    fn bar(&self, request: HelloRequest) -> Result<HelloResponse, String>;
    fn bar_server_stream(&self, request: HelloRequest, stream: &dyn PluginStreamSender<HelloResponse>) -> Result<(), String>;
    fn bar_client_stream(&self, stream: &dyn PluginStreamReceiver<HelloRequest>) -> Result<HelloResponse, String>;
    fn bar_bidi_stream(&self, stream: &dyn PluginStreamBidi<HelloRequest, HelloResponse>) -> Result<(), String>;
    fn upload_file(&self, stream: &dyn PluginStreamReceiver<FileChunk>) -> Result<FileStatus, String>;
    fn download_file(&self, request: DownloadFileRequest, stream: &dyn PluginStreamSender<FileChunk>) -> Result<(), String>;
    fn bidi_file(&self, stream: &dyn PluginStreamBidi<FileChunk, FileChunk>) -> Result<(), String>;
    fn trigger(&self, request: TriggerRequest) -> Result<HelloResponse, String>;
    fn get_goroutines(&self, request: GoroutinesRequest) -> Result<GoroutinesResponse, String>;
}

static PLUGIN_GO_GREETER_SERVICE: std::sync::OnceLock<Box<dyn GoGreeterServicePlugin>> = std::sync::OnceLock::new();

pub fn register_go_greeter_service_plugin(plugin: impl GoGreeterServicePlugin) {
    let _ = PLUGIN_GO_GREETER_SERVICE.set(Box::new(plugin));
}

fn get_go_greeter_service_plugin() -> Option<&'static dyn GoGreeterServicePlugin> {
    PLUGIN_GO_GREETER_SERVICE.get().map(|p| p.as_ref())
}


// =============================================================================
// Stream Interfaces
// =============================================================================

pub trait PluginStreamSender<T> {
    fn send(&self, msg: T) -> bool;
    fn is_cancelled(&self) -> bool;
}

pub trait PluginStreamReceiver<T> {
    fn recv(&self) -> Option<T>;
    fn is_cancelled(&self) -> bool;
}

pub trait PluginStreamBidi<Req, Resp>: PluginStreamSender<Resp> + PluginStreamReceiver<Req> {}

struct StreamSender<T> {
    ctx: Arc<StreamContext>,
    _marker: std::marker::PhantomData<T>,
}

impl<T: Message + Default> PluginStreamSender<T> for StreamSender<T> {
    fn send(&self, msg: T) -> bool {
        if self.ctx.is_closed() {
            return false;
        }
        let mut buf = Vec::new();
        if msg.encode(&mut buf).is_err() {
            return false;
        }
        // Format: [status:1][payload]
        let mut result = vec![0u8]; // success
        result.extend(buf);
        if let Ok(mut queue) = self.ctx.recv_queue.lock() {
            queue.push(result);
            self.ctx.recv_cv.notify_one();
        }
        true
    }
    
    fn is_cancelled(&self) -> bool {
        self.ctx.is_closed()
    }
}

struct StreamReceiver<T> {
    ctx: Arc<StreamContext>,
    _marker: std::marker::PhantomData<T>,
}

impl<T: Message + Default> PluginStreamReceiver<T> for StreamReceiver<T> {
    fn recv(&self) -> Option<T> {
        let mut queue = self.ctx.send_queue.lock().ok()?;
        loop {
            if self.ctx.is_closed() {
                return None;
            }
            if !queue.is_empty() {
                let data = queue.remove(0);  // FIFO order
                return T::decode(data.as_slice()).ok();
            }
            if self.ctx.send_closed.load(Ordering::SeqCst) && queue.is_empty() {
                return None;
            }
            queue = self.ctx.send_cv.wait(queue).ok()?;
        }
    }
    
    fn is_cancelled(&self) -> bool {
        self.ctx.is_closed()
    }
}

struct StreamBidi<Req, Resp> {
    sender: StreamSender<Resp>,
    receiver: StreamReceiver<Req>,
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamSender<Resp> for StreamBidi<Req, Resp> {
    fn send(&self, msg: Resp) -> bool {
        self.sender.send(msg)
    }
    fn is_cancelled(&self) -> bool {
        self.sender.is_cancelled()
    }
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamReceiver<Req> for StreamBidi<Req, Resp> {
    fn recv(&self) -> Option<Req> {
        self.receiver.recv()
    }
    fn is_cancelled(&self) -> bool {
        self.receiver.is_cancelled()
    }
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamBidi<Req, Resp> for StreamBidi<Req, Resp> {}

// =============================================================================
// C ABI Exports
// =============================================================================

#[no_mangle]
pub extern "C" fn Synurang_Free(ptr: *mut c_void) {
    if !ptr.is_null() {
        unsafe {
            let _ = Box::from_raw(ptr as *mut u8);
        }
    }
}


#[no_mangle]
pub extern "C" fn Synurang_Invoke_GoGreeterService(
    method: *const c_char,
    data: *const c_char,
    data_len: c_int,
    resp_len: *mut c_int,
) -> *mut c_char {
    let method_str = unsafe {
        if method.is_null() {
            return error_response(resp_len, "null method");
        }
        match CStr::from_ptr(method).to_str() {
            Ok(s) => s,
            Err(_) => return error_response(resp_len, "invalid method utf8"),
        }
    };
    
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        unsafe { std::slice::from_raw_parts(data as *const u8, data_len as usize).to_vec() }
    };
    
    let plugin = match get_go_greeter_service_plugin() {
        Some(p) => p,
        None => return error_response(resp_len, "plugin not registered"),
    };
    
    match method_str {
        "/example.v1.GoGreeterService/Bar" => {
            match HelloRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.bar(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/example.v1.GoGreeterService/Trigger" => {
            match TriggerRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.trigger(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/example.v1.GoGreeterService/GetGoroutines" => {
            match GoroutinesRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.get_goroutines(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        _ => error_response(resp_len, "unknown method"),
    }
}


#[no_mangle]
pub extern "C" fn Synurang_Stream_GoGreeterService_Open(method: *const c_char) -> u64 {
    let method_str = unsafe {
        if method.is_null() {
            return 0;
        }
        match CStr::from_ptr(method).to_str() {
            Ok(s) => s.to_string(),
            Err(_) => return 0,
        }
    };
    
    let plugin = match get_go_greeter_service_plugin() {
        Some(p) => p,
        None => return 0,
    };
    
    let ctx = Arc::new(StreamContext::new());
    let handle = NEXT_HANDLE.fetch_add(1, Ordering::SeqCst);
    
    {
        let mut streams = STREAMS.write().unwrap();
        streams.insert(handle, ctx.clone());
    }
    
    // Start handler thread
    let ctx_clone = ctx.clone();
    let _ = std::thread::spawn(move || {
        match method_str.as_str() {
            "/example.v1.GoGreeterService/BarServerStream" => {
                // Wait for initial request using Condvar
                let data = {
                    let mut queue = match ctx_clone.send_queue.lock() {
                        Ok(q) => q,
                        Err(_) => return,
                    };
                    loop {
                        if ctx_clone.is_closed() { return; }
                        if !queue.is_empty() {
                            break queue.remove(0);  // FIFO order
                        }
                        queue = match ctx_clone.send_cv.wait(queue) {
                            Ok(q) => q,
                            Err(_) => return,
                        };
                    }
                };
                if let Ok(req) = HelloRequest::decode(data.as_slice()) {
                    let sender = StreamSender::<HelloResponse> {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    };
                    let _ = plugin.bar_server_stream(req, &sender);
                }
                ctx_clone.close();
            }
            "/example.v1.GoGreeterService/BarClientStream" => {
                let receiver = StreamReceiver::<HelloRequest> {
                    ctx: ctx_clone.clone(),
                    _marker: std::marker::PhantomData,
                };
                if let Ok(resp) = plugin.bar_client_stream(&receiver) {
                    let sender = StreamSender::<HelloResponse> {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    };
                    let _ = sender.send(resp);
                }
                ctx_clone.close();
            }
            "/example.v1.GoGreeterService/BarBidiStream" => {
                let bidi = StreamBidi::<HelloRequest, HelloResponse> {
                    sender: StreamSender {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    },
                    receiver: StreamReceiver {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    },
                };
                let _ = plugin.bar_bidi_stream(&bidi);
                ctx_clone.close();
            }
            "/example.v1.GoGreeterService/UploadFile" => {
                let receiver = StreamReceiver::<FileChunk> {
                    ctx: ctx_clone.clone(),
                    _marker: std::marker::PhantomData,
                };
                if let Ok(resp) = plugin.upload_file(&receiver) {
                    let sender = StreamSender::<FileStatus> {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    };
                    let _ = sender.send(resp);
                }
                ctx_clone.close();
            }
            "/example.v1.GoGreeterService/DownloadFile" => {
                // Wait for initial request using Condvar
                let data = {
                    let mut queue = match ctx_clone.send_queue.lock() {
                        Ok(q) => q,
                        Err(_) => return,
                    };
                    loop {
                        if ctx_clone.is_closed() { return; }
                        if !queue.is_empty() {
                            break queue.remove(0);  // FIFO order
                        }
                        queue = match ctx_clone.send_cv.wait(queue) {
                            Ok(q) => q,
                            Err(_) => return,
                        };
                    }
                };
                if let Ok(req) = DownloadFileRequest::decode(data.as_slice()) {
                    let sender = StreamSender::<FileChunk> {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    };
                    let _ = plugin.download_file(req, &sender);
                }
                ctx_clone.close();
            }
            "/example.v1.GoGreeterService/BidiFile" => {
                let bidi = StreamBidi::<FileChunk, FileChunk> {
                    sender: StreamSender {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    },
                    receiver: StreamReceiver {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    },
                };
                let _ = plugin.bidi_file(&bidi);
                ctx_clone.close();
            }
            _ => {}
        }
    });
    
    handle
}




#[no_mangle]
pub extern "C" fn Synurang_Stream_Send(handle: u64, data: *const c_char, data_len: c_int) -> c_int {
    let ctx = match get_stream(handle) {
        Some(c) => c,
        None => return -1,
    };
    
    if ctx.is_closed() {
        return -1;
    }
    
    let bytes = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        unsafe { std::slice::from_raw_parts(data as *const u8, data_len as usize).to_vec() }
    };
    
    ctx.send_to_plugin(bytes);
    0
}

#[no_mangle]
pub extern "C" fn Synurang_Stream_Recv(
    handle: u64,
    resp_len: *mut c_int,
    status: *mut c_int,
) -> *mut c_char {
    let ctx = match get_stream(handle) {
        Some(c) => c,
        None => {
            unsafe { *status = 2; *resp_len = 0; }
            return ptr::null_mut();
        }
    };
    
    // Block for data using Condvar (no busy-wait polling)
    match ctx.recv_from_plugin() {
        Some(data) => {
            let ptr = Box::into_raw(data.clone().into_boxed_slice()) as *mut c_char;
            unsafe {
                *resp_len = data.len() as c_int;
                *status = 0;
            }
            ptr
        }
        None => {
            unsafe {
                *status = 1; // EOF
                *resp_len = 0;
            }
            ptr::null_mut()
        }
    }
}

#[no_mangle]
pub extern "C" fn Synurang_Stream_CloseSend(handle: u64) {
    if let Some(ctx) = get_stream(handle) {
        {
            let _guard = ctx.send_queue.lock();
            ctx.send_closed.store(true, Ordering::SeqCst);
        }
        ctx.send_cv.notify_all();
    }
}

#[no_mangle]
pub extern "C" fn Synurang_Stream_Close(handle: u64) {
    if let Some(ctx) = get_stream(handle) {
        ctx.close();  // This now notifies all waiters
    }
    if let Ok(mut streams) = STREAMS.write() {
        streams.remove(&handle);
    }
}


// =============================================================================
// Helper Functions
// =============================================================================

fn error_response(resp_len: *mut c_int, msg: &str) -> *mut c_char {
    let mut result = vec![1u8]; // error status
    result.extend(msg.as_bytes());
    unsafe { *resp_len = result.len() as c_int; }
    Box::into_raw(result.into_boxed_slice()) as *mut c_char
}

fn success_response(resp_len: *mut c_int, data: &[u8]) -> *mut c_char {
    let mut result = vec![0u8]; // success status
    result.extend(data);
    unsafe { *resp_len = result.len() as c_int; }
    Box::into_raw(result.into_boxed_slice()) as *mut c_char
}

// Module: example_v1

