syntax = "proto3";
package core.v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

option go_package = "github.com/ivere27/synurang/pkg/api";

// =============================================================================
// HealthService - Basic health check
// =============================================================================
service HealthService {
  rpc Ping (google.protobuf.Empty) returns (PingResponse);
}

// =============================================================================
// Messages
// =============================================================================

message PingResponse {
  google.protobuf.Timestamp timestamp = 1;
  string version = 2;
}

// =============================================================================
// Error handling
// =============================================================================
message Error {
  int32 code = 1;
  string message = 2;
  int32 grpc_code = 3;
}
